SELECT DISTINCT ald.CARR_CD, 
ald.Name, 
ald.SRVC_CD, 
ald.SRVC_DESC, 
CAST(ald.STRD_DTT AS DATE) AS STRD_DTT, 
CAST(ald.SHPD_DTT AS DATE) AS SHPD_DTT, 
CAST(ald.DLVY_DTT AS DATE) AS DLVY_DTT, 
DATEDIFF(day, CAST(ald.SHPD_DTT AS DATE), CAST(ald.DLVY_DTT AS DATE) ) as DayDiff,
DATEDIFF(month, CAST(ald.SHPD_DTT AS DATE), CAST(ald.DLVY_DTT AS DATE) ) as MonthDiff,
DATEDIFF(year, CAST(ald.SHPD_DTT AS DATE), CAST(ald.DLVY_DTT AS DATE) ) as YearDiff,

CAST(
CASE WHEN DATEDIFF(day, CAST(ald.SHPD_DTT AS DATE), CAST(ald.DLVY_DTT AS DATE))

CASE WHEN DATEDIFF(year, CAST(ald.SHPD_DTT AS DATE), CAST(ald.DLVY_DTT AS DATE) ) < 0
THEN DATEADD(year,ABS(DATEDIFF(year, CAST(ald.SHPD_DTT AS DATE), CAST(ald.DLVY_DTT AS DATE))),ald.DLVY_DTT)
ELSE ald.DLVY_DTT END 



AS DATE) AS NewDLVY_DTT,
ald.LD_LEG_ID
FROM USCTTDEV.dbo.tblActualLoadDetail ald
WHERE CAST(ald.DLVY_DTT AS DATE) < CAST(ald.SHPD_DTT AS DATE)
AND CAST(ald.SHPD_DTT AS DATE) > CAST(ald.STRD_DTT AS DATE)
ORDER BY 'YearDiff' ASC, 'MonthDiff' ASC, 'DayDiff' ASC