

WITH LoadData AS (SELECT DISTINCT ald.LD_LEG_ID,
ald.Lane,
ROW_NUMBER() OVER (PARTITION BY ald.Lane, ald.LAST_SHPG_LOC_CD ORDER BY CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END ASC, ald.LD_LEG_ID ASC) AS Ordinal,
ald.FRST_CTRY_CD,
ald.FRST_STA_CD,
ald.FRST_CTY_NAME,
CASE WHEN ald.FRST_CTRY_CD = 'USA' THEN LEFT(ald.FRST_PSTL_CD,5) ELSE ald.FRST_PSTL_CD END AS FRST_PSTL_CD,
ald.Origin_Zone,
ald.OriginPlant,
ald.LAST_CTRY_CD,
ald.LAST_STA_CD,
ald.LAST_CTY_NAME,
CASE WHEN ald.LAST_CTRY_CD = 'USA' THEN LEFT(ald.LAST_PSTL_CD,5) ELSE ald.LAST_PSTL_CD END AS LAST_PSTL_CD,
ald.Dest_Zone,
ald.DestinationPlant,
ald.LAST_SHPG_LOC_CD,
ald.LAST_SHPG_LOC_NAME,
ald.CustomerHierarchy,
ald.BU,
ald.TotalWeight,
ald.TotalVolume,
/*ald.AwardLane,
ald.AwardCarrier,*/
ald.BUSegment,
/*ald.Dedicated, 
ald.RateType,
ald.LiveLoad,*/
ald.TotalCost,
CAST(CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END AS DATE) AS Date,

CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END AS DateTime,

DATEDIFF(SECOND, LAG(CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END) OVER (PARTITION BY ald.Lane, ald.LAST_SHPG_LOC_CD ORDER BY CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END ASC, ald.LD_LEG_ID ASC), CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END) AS MinuteLag,

DATEDIFF(DAY, LAG(CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END) OVER (PARTITION BY ald.Lane, ald.LAST_SHPG_LOC_CD ORDER BY CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END ASC, ald.LD_LEG_ID ASC), CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END) AS DayLag,

LAG(ald.LD_LEG_ID) OVER (PARTITION BY ald.Lane, ald.LAST_SHPG_LOC_CD ORDER BY CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END ASC, ald.LD_LEG_ID ASC) AS PreviousLD_LEG_ID,

LAG(CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END) OVER (PARTITION BY ald.Lane, ald.LAST_SHPG_LOC_CD ORDER BY CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END ASC, ald.LD_LEG_ID ASC) AS PreviousDateTime,

LAG(CAST(CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END AS DATE)) OVER (PARTITION BY ald.Lane, ald.LAST_SHPG_LOC_CD ORDER BY CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END ASC, ald.LD_LEG_ID ASC) AS PreviousDate,

LAG(ald.TotalWeight) OVER (PARTITION BY ald.Lane, ald.LAST_SHPG_LOC_CD ORDER BY CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END ASC, ald.LD_LEG_ID ASC) AS PreviousWeight,

LAG(ald.TotalVolume) OVER (PARTITION BY ald.Lane, ald.LAST_SHPG_LOC_CD ORDER BY CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END ASC, ald.LD_LEG_ID ASC) AS PreviousVolume,

LAG(ald.TotalCost) OVER (PARTITION BY ald.Lane, ald.LAST_SHPG_LOC_CD ORDER BY CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END ASC, ald.LD_LEG_ID ASC) AS PreviousCost,

LAG(ald.LAST_SHPG_LOC_CD) OVER (PARTITION BY ald.Lane, ald.LAST_SHPG_LOC_CD ORDER BY CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END ASC, ald.LD_LEG_ID ASC) AS PreviousLAST_SHPG_LOC_CD,

LAG(ald.LAST_SHPG_LOC_NAME) OVER (PARTITION BY ald.Lane, ald.LAST_SHPG_LOC_NAME ORDER BY CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END ASC, ald.LD_LEG_ID ASC) AS PreviousLAST_SHPG_LOC_NAME,

LAG(ald.CustomerHierarchy) OVER (PARTITION BY ald.Lane, ald.CustomerHierarchy ORDER BY CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END ASC, ald.LD_LEG_ID ASC) AS PreviousCustomerHierarchy,

CASE WHEN LAG(ald.LAST_SHPG_LOC_CD) OVER (PARTITION BY ald.Lane, ald.LAST_SHPG_LOC_CD ORDER BY CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END ASC, ald.LD_LEG_ID ASC)  = ald.LAST_SHPG_LOC_CD 
AND ald.TotalVolume + LAG(ald.TotalVolume) OVER (PARTITION BY ald.Lane, ald.LAST_SHPG_LOC_CD ORDER BY CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END ASC, ald.LD_LEG_ID ASC) < 3250 

AND ald.TotalWeight + LAG(ald.TotalWeight) OVER (PARTITION BY ald.Lane, ald.LAST_SHPG_LOC_CD ORDER BY CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END ASC, ald.LD_LEG_ID ASC) < 40000 

AND DATEDIFF(DAY, LAG(CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END) OVER (PARTITION BY ald.Lane, ald.LAST_SHPG_LOC_CD ORDER BY CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END ASC, ald.LD_LEG_ID ASC), CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END) <= 7
THEN 'Yes'
ELSE 'No' END AS CanCombineWithPrevious,

CASE WHEN LAG(ald.LD_LEG_ID) OVER (PARTITION BY ald.Lane, ald.LAST_SHPG_LOC_CD ORDER BY CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END ASC, ald.LD_LEG_ID ASC) IS NULL THEN 'New Lane or Customer'

WHEN DATEDIFF(DAY, LAG(CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END) OVER (PARTITION BY ald.Lane, ald.LAST_SHPG_LOC_CD ORDER BY CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END ASC, ald.LD_LEG_ID ASC), CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END) > 7 THEN 'More than 1 Week Apart'

WHEN ald.TotalVolume + LAG(ald.TotalVolume) OVER (PARTITION BY ald.Lane, ald.LAST_SHPG_LOC_CD ORDER BY CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END ASC, ald.LD_LEG_ID ASC) > 3250 THEN 'Over Cube Limit'

WHEN ald.TotalWeight + LAG(ald.TotalWeight) OVER (PARTITION BY ald.Lane, ald.LAST_SHPG_LOC_CD ORDER BY CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.CRTD_DTT END ASC, ald.LD_LEG_ID ASC) > 40000 THEN 'Over Weight Limit'

ELSE 'Can Combine' END AS CombineReason


FROM USCTTDEV.dbo.tblActualLoadDetail ald
WHERE ald.EQMT_TYP <> 'LTL'
/*AND ald.Lane = 'CAONTARI-5CA95330'*/
AND ald.TotalVolume < 2000
AND ald.SHPD_DTT BETWEEN '1/4/2021' AND DATEADD(wk,DATEDIFF(wk,7,GETDATE()),6)
AND ald.BUSegment NOT IN ('Wadding','NFG','NONWOVENS')
/*AND YEAR(CAST(CASE WHEN ald.SHPD_DTT IS NOT NULL THEN ald.SHPD_DTT
WHEN ald.STRD_DTT IS NOT NULL THEN ald.STRD_DTT
ELSE ald.SHPD_DTT END AS DATE)) >= YEAR(GETDATE()) - 1*/
)

, LoadDataAgg AS (
SELECT 
LoadData.Ordinal AS LowCubeOrdinal,
LoadData.LD_LEG_ID AS LowCubeLD_LEG_ID,
LoadData.Lane AS LowCubeLane,
LoadData.BU AS LowCubeBU,
LoadData.Origin_Zone AS LowCubeOrigin_Zone,
LoadData.OriginPlant AS LowCubeOriginPlant,
LoadData.FRST_CTRY_CD AS LowCubeFRST_CTRY_CD,
LoadData.FRST_STA_CD AS LowCubeFRST_STA_CD,
LoadData.FRST_CTY_NAME AS LowCubeFRST_CTY_NAME,
LoadData.FRST_PSTL_CD AS LowCubeFRST_PSTL_CD,
LoadData.Dest_Zone AS LowCubeDest_Zone,
LoadData.DestinationPlant AS LowCubeDestinationPlant,
LoadData.LAST_CTRY_CD AS LowCubeLAST_CTRY_CD,
LoadData.LAST_STA_CD AS LowCubeLAST_STA_CD,
LoadData.LAST_CTY_NAME AS LowCubeLAST_CTY_NAME,
LoadData.LAST_PSTL_CD AS LowCubeLAST_PSTL_CD,
LoadData.LAST_SHPG_LOC_CD AS LowCubeLAST_SHPG_LOC_CD,
LoadData.LAST_SHPG_LOC_NAME AS LowCubeLAST_SHPG_LOC_NAME,
LoadData.TotalWeight AS LowCubeTotalWeight,
LoadData.TotalVolume AS LowCubeTotalVolume,
LoadData.BUSegment AS LowCubeBUSegment,
LoadData.TotalCost AS LowCubeTotalCost,
LoadData.Date AS LowCubeDate,
CASE WHEN TheDate BETWEEN DATEADD(wk,DATEDIFF(wk,7,GETDATE()),0) AND DATEADD(wk,DATEDIFF(wk,7,GETDATE()),6) THEN 'Last Week'
ELSE CAST(DATEDIFF(WEEK, da.TheFirstOfWeekMon, CAST(DATEADD(wk, DATEDIFF(wk,0,GETDATE()), 0) AS DATE)) AS VARCHAR(2)) + ' Weeks Ago' END AS LowCubeDateFlag ,
/*DATEDIFF(WEEK, da.TheFirstOfWeekMon, CAST(DATEADD(wk, DATEDIFF(wk,0,GETDATE()), 0) AS DATE)) AS WeekLag,*/
LoadData.DateTime AS LowCubeDateTime,
1 AS LoadCount,
da.TheFirstOfWeekMon AS LowCubeFirstOfWeekMonday,
LoadData.PreviousDate AS LowCubePreviousDate,
LoadData.PreviousDateTime AS LowCubePreviousDateTime,
LoadData.MinuteLag AS LowCubeMinuteLag,
LoadData.DayLag AS LowCubeDayLag,
LoadData.PreviousLD_LEG_ID AS LowCubePreviousLD_LEG_ID,
LoadData.PreviousWeight AS LowCubePreviousWeight,
LoadData.PreviousVolume AS LowCubePreviousVolume,
LoadData.PreviousCost AS LowCubePreviousCost,
LoadData.PreviousLAST_SHPG_LOC_CD AS LowCubePreviousLAST_SHPG_LOC_CD,
LoadData.PreviousLAST_SHPG_LOC_NAME AS LowCubePreviousLAST_SHPG_LOC_NAME,
LoadData.PreviousCustomerHierarchy AS LowCubePreviousCustomerHierarchy,
/*LoadData.CanCombineWithPrevious,*/

CASE WHEN DATEADD(DD, 2 - DATEPART(DW, DATEADD(DD, -1, PreviousDate)), DATEADD(DD, -1, PreviousDate)) = DATEADD(DD, 2 - DATEPART(DW, DATEADD(DD, -1, Date)), DATEADD(DD, -1, Date)) AND LoadData.CanCombineWithPrevious = 'Yes' THEN 'Yes' ELSE 'No' END AS LowCubeCanCombineWithPrevious,

/*LoadData.CombineReason,*/

CASE WHEN DATEADD(DD, 2 - DATEPART(DW, DATEADD(DD, -1, PreviousDate)), DATEADD(DD, -1, PreviousDate)) <> DATEADD(DD, 2 - DATEPART(DW, DATEADD(DD, -1, Date)), DATEADD(DD, -1, Date)) THEN 'New Monday Week' ELSE LoadData.CombineReason END AS LowCubeCombineReason,

/*CASE WHEN LoadData.CanCombineWithPrevious = 'Yes' AND LoadData.DayLag = 0 THEN 'Same Day'
WHEN LoadData.CanCombineWithPrevious = 'Yes' AND LoadData.DayLag = 1 THEN '1 Day Apart'
WHEN  LoadData.CanCombineWithPrevious = 'Yes' AND LoadData.DayLag > 1 THEN CAST(LoadData.DayLag AS VARCHAR(2)) + ' Days Apart' END AS CombineReasonFlag,*/

CASE WHEN DATEADD(DD, 2 - DATEPART(DW, DATEADD(DD, -1, PreviousDate)), DATEADD(DD, -1, PreviousDate)) = DATEADD(DD, 2 - DATEPART(DW, DATEADD(DD, -1, Date)), DATEADD(DD, -1, Date)) THEN
CASE WHEN LoadData.CanCombineWithPrevious = 'Yes' AND LoadData.DayLag = 0 THEN '0 Same Day'
WHEN LoadData.CanCombineWithPrevious = 'Yes' AND LoadData.DayLag = 1 THEN '1 Day Apart'
WHEN  LoadData.CanCombineWithPrevious = 'Yes' AND LoadData.DayLag > 1 THEN CAST(LoadData.DayLag AS VARCHAR(2)) + ' Days Apart' END
END AS LowCubeCombineReasonFlag,

/*CASE WHEN CanCombineWIthPrevious = 'Yes' THEN 1 ELSE NULL END AS CanCombineCount,*/

CASE WHEN DATEADD(DD, 2 - DATEPART(DW, DATEADD(DD, -1, PreviousDate)), DATEADD(DD, -1, PreviousDate)) = DATEADD(DD, 2 - DATEPART(DW, DATEADD(DD, -1, Date)), DATEADD(DD, -1, Date)) THEN CASE WHEN CanCombineWIthPrevious = 'Yes' THEN 1 ELSE NULL END  END AS LowCubeCanCombineCount,

/*CASE WHEN CanCombineWIthPrevious = 'Yes' THEN
	CASE WHEN LoadData.PreviousCost > LoadData.TotalCost THEN LoadData.PreviousCost ELSE LoadData.TotalCost END
ELSE NULL END AS CanCombineCost,*/

CASE WHEN DATEADD(DD, 2 - DATEPART(DW, DATEADD(DD, -1, PreviousDate)), DATEADD(DD, -1, PreviousDate)) = DATEADD(DD, 2 - DATEPART(DW, DATEADD(DD, -1, Date)), DATEADD(DD, -1, Date)) THEN 
	CASE WHEN CanCombineWIthPrevious = 'Yes' THEN
	CASE WHEN LoadData.PreviousCost > LoadData.TotalCost THEN LoadData.PreviousCost ELSE LoadData.TotalCost END
ELSE NULL END
END AS LowCubeCanCombineCost,

/*CASE WHEN CanCombineWIthPrevious = 'Yes' THEN LoadData.PreviousVolume + LoadData.TotalVolume ELSE NULL END AS CanCombineVolume,*/

CASE WHEN DATEADD(DD, 2 - DATEPART(DW, DATEADD(DD, -1, PreviousDate)), DATEADD(DD, -1, PreviousDate)) = DATEADD(DD, 2 - DATEPART(DW, DATEADD(DD, -1, Date)), DATEADD(DD, -1, Date)) THEN 
CASE WHEN CanCombineWIthPrevious = 'Yes' THEN LoadData.PreviousVolume + LoadData.TotalVolume ELSE NULL END
END AS LowCubeCanCombineVolume

FROM LoadData
INNER JOIN USCTTDEV.dbo.tblDates da ON da.TheDate = LoadData.Date
/*WHERE LoadData.Lane = 'ARCONWAY-5MS39601'*/
)
SELECT LoadDataAgg.*
FROM LoadDataAgg
ORDER BY LoadDataAgg.LowCubeLane ASC,
LoadDataAgg.LowCubeLAST_SHPG_LOC_CD ASC, 
LoadDataAgg.LowCubeDateTime ASC,
LoadDataAgg.LowCubeLD_LEG_ID ASC