
SELECT DISTINCT 
regionAgg.Region,
COUNT(DISTINCT regionAgg.LaneID) AS LaneCount,

/*
This is an aggregation of last year
*/
SUM(regionAgg.LY_LANE_VOL) AS LY_LANE_VOL,
SUM(regionAgg.LY_VOL) AS LY_VOL,
CAST(ROUND(SUM(regionAgg.LY_VOL) / SUM(CAST(LY_LANE_VOL AS NUMERIC(10,2))), 4) AS NUMERIC(10,4)) AS LY_AWARD_PCT,
SUM(regionAgg.LY_COST) AS LY_COST,

/*
This is an aggregation of the current bid
*/
SUM(regionAgg.TY_LANE_BID_VOL) AS TY_LANE_BID_VOL,
SUM(regionAgg.TY_BID_VOL) AS TY_BID_VOL,
CAST(ROUND(SUM(regionAgg.TY_BID_VOL) / SUM(CAST(TY_LANE_BID_VOL AS NUMERIC(10,2))), 4) AS NUMERIC(10,4)) AS TY_BID_AWARD_PCT,
SUM(regionAgg.TY_BID_COST) AS TY_BID_COST,

/*
This is an aggregation of the most current state
*/
SUM(regionAgg.CUR_LANE_VOL) AS CUR_LANE_VOL,
SUM(regionAgg.CUR_AWARD_VOL) AS CUR_AWARD_VOL,
CAST(ROUND(SUM(regionAgg.CUR_AWARD_VOL) / SUM(CAST(CUR_LANE_VOL AS NUMERIC(10,2))), 4) AS NUMERIC(10,4)) AS CUR_AWARD_PCT,
SUM(regionAgg.CUR_COST) AS CUR_COST,
SUM(regionAgg.CUR_V_BID_COST) AS CUR_V_BID_COST

FROM(
SELECT DISTINCT 
laneAgg.LaneID,
laneAgg.Lane,
laneAgg.Origin,
laneAgg.Dest,
laneAgg.[Order Type],
laneAgg.Region,
CAST(AVG(laneAgg.Miles) AS NUMERIC(10,2)) AS Miles,

/*
Last year cost details
*/
AVG(laneAgg.LY_LANE_VOL) AS LY_LANE_VOL,
SUM(laneAgg.LY_VOL) AS LY_VOL,
SUM(laneAgg.LY_AWARD_PCT) AS LY_AWARD_PCT,
CAST(ROUND((SUM(laneAgg.LY_COST) / AVG(laneAgg.LY_LANE_VOL) ) / CAST(AVG(laneAgg.Miles) AS NUMERIC(10,2)),2) AS NUMERIC(10,2)) AS LY_WGT_RPM,
SUM(laneAgg.LY_COST) AS LY_COST,

/*
Current costs
*/
AVG(laneAgg.TY_LANE_BID_VOL) AS TY_LANE_BID_VOL,
SUM(laneAgg.TY_BID_VOL) AS TY_BID_VOL,
SUM(laneAgg.TY_BID_AWARD_PCT) AS TY_BID_AWARD_PCT,
SUM(laneAgg.TY_V_LY_BID_LOAD_PCT) AS TY_V_LY_BID_LOAD_PCT,
CAST(ROUND((SUM(laneAgg.TY_BID_COST) / AVG(laneAgg.TY_LANE_BID_VOL) ) / CAST(AVG(laneAgg.Miles) AS NUMERIC(10,2)),2) AS NUMERIC(10,2)) AS TY_BID_WGT_RPM,
SUM(laneAgg.TY_BID_COST) AS TY_BID_COST,

/*
This year Bid cost details
*/
AVG(laneAgg.CUR_LANE_VOL) AS CUR_LANE_VOL,
SUM(laneAgg.CUR_AWARD_VOL) AS CUR_AWARD_VOL,
SUM(laneAgg.CUR_V_BID_LOADS) AS CUR_V_BID_LOADS,
SUM(laneAgg.CUR_AWARD_PCT) AS CUR_BID_AWARD_PCT,
SUM(laneAgg.CUR_V_BID_LOAD_PCT) AS CUR_V_BID_LOAD_PCT,
CAST(ROUND((SUM(laneAgg.CUR_COST) / AVG(laneAgg.CUR_LANE_VOL) ) / CAST(AVG(laneAgg.Miles) AS NUMERIC(10,2)),2) AS NUMERIC(10,2)) AS CUR_WGT_RPM,
SUM(laneAgg.CUR_COST) AS CUR_COST,
SUM(CUR_V_BID_COST) AS CUR_V_BID_COST


FROM(
/*
SELECT TOP 20 * FROM USCTTDEV.dbo.tblBidAppLanesRFP2021 WHERE Lane = 'ALFAIRHO-5AL36610'
SELECT TOP 20 * FROM USCTTDEV.dbo.tblBidAppRatesRFP2021 WHERE Lane = 'ALFAIRHO-5AL36610'
SELECT TOP 20 * FROM USCTTDEV.dbo.tblBidAppLanes WHERE Lane = 'ALFAIRHO-5AL36610'
SELECT TOP 20 * FROM USCTTDEV.dbo.tblBidAppRates WHERE Lane = 'ALFAIRHO-5AL36610'
*/
SELECT DISTINCT 
/*
Lane Details
*/
bal.LaneID,
bal.Lane,
bal.Origin,
bal.Dest,
bal.[Order Type],
ra.Region,
ca.CARR_CD,
ca.Name,
bar.SCAC,
ca.SRVC_DESC,
CAST(bal.MILES AS NUMERIC(18,2)) Miles,

/*
Last Year Volume
*/
CAST(bal.HISTORICAL_LOADS AS INT) AS LY_LANE_VOL,
CAST(LY_VOL AS INT) LY_VOL,
CAST(ROUND( CAST(LY_VOL AS INT) / CAST(bal.HISTORICAL_LOADS AS NUMERIC(18,2)) ,2) AS NUMERIC(18,2)) AS LY_AWARD_PCT,
CAST(LY_RPM AS NUMERIC(18,2)) LY_RPM,
CAST((ROUND(CAST(LY_RPM AS NUMERIC(18,2)) * CASE WHEN bar.[Min Charge] IS NULL THEN CAST(bal.Miles AS NUMERIC(18,2)) ELSE 1 END * LY_VOL,2)) AS NUMERIC(18,2)) AS LY_COST,
bal.BID_LOADS AS TY_LANE_BID_VOL,


/*
This Year Bid Volume
This is the allocated output that came from Coupa
*/
bar.BID_AWARD_LDS AS TY_BID_VOL,
CAST(ROUND( CAST(bar.BID_AWARD_LDS AS INT) / CAST(bal.BID_LOADS AS NUMERIC(18,2)),2) AS NUMERIC(18,2)) AS TY_BID_AWARD_PCT,
CAST(ROUND(CASE WHEN BID_AWARD_LDS IS NULL AND LY_VOL IS NULL THEN NULL
WHEN BID_AWARD_LDS IS NOT NULL AND LY_VOL IS NULL THEN 1
WHEN BID_AWARD_LDS IS NULL AND LY_VOL IS NOT NULL THEN -1
ELSE (BID_AWARD_LDS - LY_VOL)/LY_VOL END,2) AS NUMERIC(10,2)) AS TY_V_LY_BID_LOAD_PCT,
CAST(bar.BID_RPM AS NUMERIC(18,2)) AS TY_BID_RPM,
CAST(CASE WHEN bar.BID_AWARD_LDS IS NOT NULL THEN ROUND(CASE WHEN bar.[Min Charge] IS NULL THEN bal.MILES ELSE 1 END * CAST(bar.BID_RPM AS NUMERIC(18,2)) ,2) END AS NUMERIC(10,2)) * bar.BID_AWARD_LDS AS TY_BID_COST,

/*
Updated Loads
This is the absolute current state
*/
bal.UPDATED_LOADS AS CUR_LANE_VOL,
bar.AWARD_LDS AS CUR_AWARD_VOL,
CAST(ROUND(CASE WHEN bar.AWARD_LDS IS NULL AND bar.BID_AWARD_LDS IS NULL THEN NULL
WHEN bar.AWARD_LDS IS NOT NULL AND bar.BID_AWARD_LDS IS NULL THEN bar.AWARD_LDS
WHEN bar.AWARD_LDS IS NULL AND bar.BID_AWARD_LDS IS NOT NULL THEN 0 - bar.BID_AWARD_LDS
ELSE (bar.AWARD_LDS - bar.BID_AWARD_LDS) END,2) AS NUMERIC(10,2)) AS CUR_V_BID_LOADS,
bar.AWARD_PCT AS CUR_AWARD_PCT,
CAST(ROUND(CASE WHEN bar.AWARD_LDS IS NULL AND bar.BID_AWARD_LDS IS NULL THEN NULL
WHEN bar.AWARD_LDS IS NOT NULL AND bar.BID_AWARD_LDS IS NULL THEN 1
WHEN bar.AWARD_LDS IS NULL AND bar.BID_AWARD_LDS IS NOT NULL THEN -1
ELSE (CAST(bar.AWARD_LDS AS NUMERIC(10,2)) - bar.BID_AWARD_LDS)/bar.BID_AWARD_LDS END,2) AS NUMERIC(10,2)) AS CUR_V_BID_LOAD_PCT,
CASE WHEN bar.ChargeType = 'Rate Per Mile' THEN bar.CUR_RPM ELSE bar.[Min Charge] END AS CUR_RPM,
CAST(CASE WHEN bar.AWARD_LDS IS NOT NULL THEN ROUND(CASE WHEN bar.[Min Charge] IS NULL THEN bal.MILES  ELSE 1 END * CAST(CASE WHEN bar.ChargeType = 'Rate Per Mile' THEN bar.CUR_RPM ELSE bar.[Min Charge] END AS NUMERIC(18,2)) ,2) END AS NUMERIC(10,2)) * bar.AWARD_LDS AS CUR_COST,
CAST(ROUND(CASE WHEN bar.AWARD_LDS IS NULL AND bar.BID_AWARD_LDS IS NULL THEN NULL
WHEN bar.AWARD_LDS IS NOT NULL AND bar.BID_AWARD_LDS IS NULL THEN CAST(CASE WHEN bar.AWARD_LDS IS NOT NULL THEN ROUND(CASE WHEN bar.[Min Charge] IS NULL THEN bal.MILES  ELSE 1 END * CAST(CASE WHEN bar.ChargeType = 'Rate Per Mile' THEN bar.CUR_RPM ELSE bar.[Min Charge] END AS NUMERIC(18,2)) ,2) END AS NUMERIC(10,2)) * bar.AWARD_LDS
WHEN bar.AWARD_LDS IS NULL AND bar.BID_AWARD_LDS IS NOT NULL THEN 0 - CAST(CASE WHEN bar.BID_AWARD_LDS IS NOT NULL THEN ROUND(CASE WHEN bar.[Min Charge] IS NULL THEN bal.MILES  ELSE 1 END* CAST(bar.BID_RPM AS NUMERIC(18,2)) ,2) END AS NUMERIC(10,2)) * bar.BID_AWARD_LDS
ELSE  
CAST(CASE WHEN bar.AWARD_LDS IS NOT NULL THEN ROUND(CASE WHEN bar.[Min Charge] IS NULL THEN bal.MILES  ELSE 1 END * CAST(CASE WHEN bar.ChargeType = 'Rate Per Mile' THEN bar.CUR_RPM ELSE bar.[Min Charge] END AS NUMERIC(18,2)) ,2) END AS NUMERIC(10,2)) * bar.AWARD_LDS
- CAST(CASE WHEN bar.BID_AWARD_LDS IS NOT NULL THEN ROUND(CASE WHEN bar.[Min Charge] IS NULL THEN bal.MILES ELSE 1 END * CAST(bar.BID_RPM AS NUMERIC(18,2)) ,2) END AS NUMERIC(10,2)) * bar.BID_AWARD_LDS 
END,2) AS NUMERIC(10,2)) AS CUR_V_BID_COST

FROM USCTTDEV.dbo.tblBidAppRatesRFP2021 bar
INNER JOIN USCTTDEV.dbo.tblBidAppLanesRFP2021 bal ON bal.LaneID = bar.LaneID
INNER JOIN USCTTDEV.dbo.tblCarriers ca ON ca.SRVC_CD = bar.SCAC
INNER JOIN USCTTDEV.dbo.tblRegionalAssignments ra ON ra.StateAbbv = CASE WHEN bal.[Order Type] LIKE '%INBOUND%' THEN RIGHT(bal.Dest,2) ELSE RIGHT(bal.Origin,2) END

/*WHERE bal.LaneID = 910*/

GROUP BY  bal.LaneID,
bal.Lane,
bal.Origin,
bal.Dest,
bal.[Order Type],
ra.Region,
ca.CARR_CD,
ca.Name,
bar.SCAC,
ca.SRVC_DESC,
CAST(bal.MILES AS NUMERIC(18,2)),

/*
Last Year Volume
*/
CAST(bal.HISTORICAL_LOADS AS INT) ,
CAST(LY_VOL AS INT) ,
CAST(ROUND( CAST(LY_VOL AS INT) / CAST(bal.HISTORICAL_LOADS AS NUMERIC(18,2)) ,2) AS NUMERIC(18,2)) ,
CAST(LY_RPM AS NUMERIC(18,2)),
CAST((ROUND(CAST(LY_RPM AS NUMERIC(18,2)) * CASE WHEN bar.[Min Charge] IS NULL THEN CAST(bal.Miles AS NUMERIC(18,2)) ELSE 1 END * LY_VOL,2)) AS NUMERIC(18,2)),
bal.BID_LOADS,


/*
This Year Bid Volume
This is the allocated output that came from Coupa
*/
bar.BID_AWARD_LDS,
CAST(ROUND( CAST(bar.BID_AWARD_LDS AS INT) / CAST(bal.BID_LOADS AS NUMERIC(18,2)),2) AS NUMERIC(18,2)),
CAST(ROUND(CASE WHEN BID_AWARD_LDS IS NULL AND LY_VOL IS NULL THEN NULL
WHEN BID_AWARD_LDS IS NOT NULL AND LY_VOL IS NULL THEN 1
WHEN BID_AWARD_LDS IS NULL AND LY_VOL IS NOT NULL THEN -1
ELSE (BID_AWARD_LDS - LY_VOL)/LY_VOL END,2) AS NUMERIC(10,2)),
CAST(bar.BID_RPM AS NUMERIC(18,2)),
CAST(CASE WHEN bar.BID_AWARD_LDS IS NOT NULL THEN ROUND(CASE WHEN bar.[Min Charge] IS NULL THEN bal.MILES ELSE 1 END * CAST(bar.BID_RPM AS NUMERIC(18,2)) ,2) END AS NUMERIC(10,2)) * bar.BID_AWARD_LDS,

/*
Updated Loads
This is the absolute current state
*/
bal.UPDATED_LOADS,
bar.AWARD_LDS,
CAST(ROUND(CASE WHEN bar.AWARD_LDS IS NULL AND bar.BID_AWARD_LDS IS NULL THEN NULL
WHEN bar.AWARD_LDS IS NOT NULL AND bar.BID_AWARD_LDS IS NULL THEN bar.AWARD_LDS
WHEN bar.AWARD_LDS IS NULL AND bar.BID_AWARD_LDS IS NOT NULL THEN 0 - bar.BID_AWARD_LDS
ELSE (bar.AWARD_LDS - bar.BID_AWARD_LDS) END,2) AS NUMERIC(10,2)),
bar.AWARD_PCT,
CAST(ROUND(CASE WHEN bar.AWARD_LDS IS NULL AND bar.BID_AWARD_LDS IS NULL THEN NULL
WHEN bar.AWARD_LDS IS NOT NULL AND bar.BID_AWARD_LDS IS NULL THEN 1
WHEN bar.AWARD_LDS IS NULL AND bar.BID_AWARD_LDS IS NOT NULL THEN -1
ELSE (CAST(bar.AWARD_LDS AS NUMERIC(10,2)) - bar.BID_AWARD_LDS)/bar.BID_AWARD_LDS END,2) AS NUMERIC(10,2)),
CASE WHEN bar.ChargeType = 'Rate Per Mile' THEN bar.CUR_RPM ELSE bar.[Min Charge] END,
CAST(CASE WHEN bar.AWARD_LDS IS NOT NULL THEN ROUND(CASE WHEN bar.[Min Charge] IS NULL THEN bal.MILES  ELSE 1 END * CAST(CASE WHEN bar.ChargeType = 'Rate Per Mile' THEN bar.CUR_RPM ELSE bar.[Min Charge] END AS NUMERIC(18,2)) ,2) END AS NUMERIC(10,2)) * bar.AWARD_LDS,
CAST(ROUND(CASE WHEN bar.AWARD_LDS IS NULL AND bar.BID_AWARD_LDS IS NULL THEN NULL
WHEN bar.AWARD_LDS IS NOT NULL AND bar.BID_AWARD_LDS IS NULL THEN CAST(CASE WHEN bar.AWARD_LDS IS NOT NULL THEN ROUND(CASE WHEN bar.[Min Charge] IS NULL THEN bal.MILES  ELSE 1 END * CAST(CASE WHEN bar.ChargeType = 'Rate Per Mile' THEN bar.CUR_RPM ELSE bar.[Min Charge] END AS NUMERIC(18,2)) ,2) END AS NUMERIC(10,2)) * bar.AWARD_LDS
WHEN bar.AWARD_LDS IS NULL AND bar.BID_AWARD_LDS IS NOT NULL THEN 0 - CAST(CASE WHEN bar.BID_AWARD_LDS IS NOT NULL THEN ROUND(CASE WHEN bar.[Min Charge] IS NULL THEN bal.MILES  ELSE 1 END* CAST(bar.BID_RPM AS NUMERIC(18,2)) ,2) END AS NUMERIC(10,2)) * bar.BID_AWARD_LDS
ELSE  
CAST(CASE WHEN bar.AWARD_LDS IS NOT NULL THEN ROUND(CASE WHEN bar.[Min Charge] IS NULL THEN bal.MILES  ELSE 1 END * CAST(CASE WHEN bar.ChargeType = 'Rate Per Mile' THEN bar.CUR_RPM ELSE bar.[Min Charge] END AS NUMERIC(18,2)) ,2) END AS NUMERIC(10,2)) * bar.AWARD_LDS
- CAST(CASE WHEN bar.BID_AWARD_LDS IS NOT NULL THEN ROUND(CASE WHEN bar.[Min Charge] IS NULL THEN bal.MILES ELSE 1 END * CAST(bar.BID_RPM AS NUMERIC(18,2)) ,2) END AS NUMERIC(10,2)) * bar.BID_AWARD_LDS 
END,2) AS NUMERIC(10,2))

) laneAgg

GROUP BY laneAgg.LaneID,
laneAgg.Lane,
laneAgg.Origin,
laneAgg.Dest,
laneAgg.[Order Type],
laneAgg.Region

)regionAgg

GROUP BY regionAgg.Region

ORDER BY regionAgg.Region ASC 