SELECT DISTINCT
	IA_DIST_LOADS.LOAD_ID as LoadNumber, 
	Count(distinct IA_DIST_LOADS.EVENT_LOG_DT) as LoadCount,
    
    CASE WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='ACPD' THEN 'MANUALLY ACCEPTED'
    WHEN IA_EVNT_TYPE.EVNT_TYPE_CODE='TENDCNCL' AND	IA_EXCEPTION_CODE.EXCEPTION_CODE='PLND' THEN 'TENDER CANCELLED' 
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='REJD' THEN 'TENDER REJECTED'
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='REVS' THEN 'CONFIRM REVERSAL'
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='LUNS' THEN 'LOAD UNSUSPENDED'
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='DKD_' THEN 'DOCK DELETED'
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='DKC_' THEN 'DOCK CREATED'
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='DKH_' THEN 'DOCK CHANGED'
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='APD_' THEN 'APPOINTMENT DELETED'
    WHEN IA_EVNT_TYPE.EVNT_TYPE_CODE<>'TENDCNCL' AND IA_EXCEPTION_CODE.EXCEPTION_CODE='PLND' THEN 'MANUALLY PLANNED'
    WHEN IA_EVNT_TYPE.EVNT_TYPE_CODE IN('TENDFRST','TENDOTHER') AND IA_EXCEPTION_CODE.EXCEPTION_CODE='TNRD' THEN 'MANUALLY TENDERED'
    END AS Reason,
    
    CASE WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='ACPD' THEN 1
    WHEN IA_EVNT_TYPE.EVNT_TYPE_CODE='TENDCNCL' AND	IA_EXCEPTION_CODE.EXCEPTION_CODE='PLND' THEN 2 
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='REJD' THEN 3
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='REVS' THEN 4
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='LUNS' THEN 5
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='DKD_' THEN 6
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='DKC_' THEN 7
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='DKH_' THEN 8
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='APD_' THEN 9
    WHEN IA_EVNT_TYPE.EVNT_TYPE_CODE<>'TENDCNCL' AND IA_EXCEPTION_CODE.EXCEPTION_CODE='PLND' THEN 10
    WHEN IA_EVNT_TYPE.EVNT_TYPE_CODE IN('TENDFRST','TENDOTHER') AND IA_EXCEPTION_CODE.EXCEPTION_CODE='TNRD' THEN 11
    END AS Ordinal

FROM  
	IA_DIST_LOADS IA_DIST_LOADS 
    JOIN IA_EXCEPTION_CODE ON IA_EXCEPTION_CODE.EXCPT_CODE_KEY = IA_DIST_LOADS.EXCPT_CODE_KEY
    JOIN IA_USERS ON IA_USERS.USER_KEY = IA_DIST_LOADS.EVNT_USER_KEY
    JOIN IA_EVNT_TYPE ON IA_EVNT_TYPE.EVNT_TYPE_KEY = IA_DIST_LOADS.EVNT_TYPE_KEY

WHERE 
	(IA_DIST_LOADS.EVENT_LOG_DT>=add_months(trunc(SYSDATE, 'mm'), - 1)) AND 
	(
    (IA_EXCEPTION_CODE.EXCEPTION_CODE='ACPD') 
    OR (IA_EVNT_TYPE.EVNT_TYPE_CODE='TENDCNCL') AND	(IA_EXCEPTION_CODE.EXCEPTION_CODE='PLND')
    OR (IA_EXCEPTION_CODE.EXCEPTION_CODE='REJD')
    OR (IA_EXCEPTION_CODE.EXCEPTION_CODE='REVS')
    OR (IA_EXCEPTION_CODE.EXCEPTION_CODE='LUNS')
    OR (IA_EXCEPTION_CODE.EXCEPTION_CODE='DKD_')
    OR (IA_EXCEPTION_CODE.EXCEPTION_CODE='DKC_')
    OR (IA_EXCEPTION_CODE.EXCEPTION_CODE='DKH_')
    OR (IA_EXCEPTION_CODE.EXCEPTION_CODE='APD_')
    OR (IA_EXCEPTION_CODE.EXCEPTION_CODE='PLND')
    OR (IA_EVNT_TYPE.EVNT_TYPE_CODE IN('TENDFRST','TENDOTHER')) AND (IA_EXCEPTION_CODE.EXCEPTION_CODE='TNRD')
    )
    AND (substr(USER_LOGIN,1,1) Not In ('*','9'))

GROUP BY
	IA_DIST_LOADS.LOAD_ID, 
    CASE WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='ACPD' THEN 'MANUALLY ACCEPTED'
    WHEN IA_EVNT_TYPE.EVNT_TYPE_CODE='TENDCNCL' AND	IA_EXCEPTION_CODE.EXCEPTION_CODE='PLND' THEN 'TENDER CANCELLED' 
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='REJD' THEN 'TENDER REJECTED'
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='REVS' THEN 'CONFIRM REVERSAL'
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='LUNS' THEN 'LOAD UNSUSPENDED'
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='DKD_' THEN 'DOCK DELETED'
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='DKC_' THEN 'DOCK CREATED'
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='DKH_' THEN 'DOCK CHANGED'
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='APD_' THEN 'APPOINTMENT DELETED'
    WHEN IA_EVNT_TYPE.EVNT_TYPE_CODE<>'TENDCNCL' AND IA_EXCEPTION_CODE.EXCEPTION_CODE='PLND' THEN 'MANUALLY PLANNED'
    WHEN IA_EVNT_TYPE.EVNT_TYPE_CODE IN('TENDFRST','TENDOTHER') AND IA_EXCEPTION_CODE.EXCEPTION_CODE='TNRD' THEN 'MANUALLY TENDERED'
    END,
    CASE WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='ACPD' THEN 1
    WHEN IA_EVNT_TYPE.EVNT_TYPE_CODE='TENDCNCL' AND	IA_EXCEPTION_CODE.EXCEPTION_CODE='PLND' THEN 2 
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='REJD' THEN 3
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='REVS' THEN 4
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='LUNS' THEN 5
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='DKD_' THEN 6
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='DKC_' THEN 7
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='DKH_' THEN 8
    WHEN IA_EXCEPTION_CODE.EXCEPTION_CODE='APD_' THEN 9
    WHEN IA_EVNT_TYPE.EVNT_TYPE_CODE<>'TENDCNCL' AND IA_EXCEPTION_CODE.EXCEPTION_CODE='PLND' THEN 10
    WHEN IA_EVNT_TYPE.EVNT_TYPE_CODE IN('TENDFRST','TENDOTHER') AND IA_EXCEPTION_CODE.EXCEPTION_CODE='TNRD' THEN 11
    END

ORDER BY 
	IA_DIST_LOADS.LOAD_ID, Ordinal
