Select ORIGIN_ID, DESTINATION_ID, Equip_TYPE, MAX(FROM_DATE) As FROM_DATE, MAX(TO_DATE) As TO_DATE, sum(AWARD_PCTOF_LANE) as Awd_PCT,
ORIGIN_ZONE_ID, DESTINATION_ZONE_ID, sum(WEEKLY_LANE_VOLUME) as Awd_VOL, TO_CHAR(SUM(AWARD_PCTOF_LANE*LINEHAUL_RATE_PER_MILE)/SUM(AWARD_PCTOF_LANE), '$9,999.00') as Awd_Weight_RPM, 
(trunc(SYSDATE) - MAX(trunc(FROM_DATE))) as Days_Active

from abpp_laneserviceawards
WHERE AWARD_PCTOF_LANE > 0

/*
AND ORIGIN_ID = '2827-MB02'
AND DESTINATION_ID = '2299-DC01' 
*/
GROUP BY ORIGIN_ID, DESTINATION_ID, Equip_TYPE, FROM_DATE, TO_DATE, 
ORIGIN_ZONE_ID, DESTINATION_ZONE_ID

ORDER BY ORIGIN_ID, DESTINATION_ID, Equip_TYPE, FROM_DATE, TO_DATE, 
ORIGIN_ZONE_ID, DESTINATION_ZONE_ID