WITH
/********************************************************************************************************************
/* MANUAL CUSTOMER GROUPINGS
/********************************************************************************************************************/
CUSTOMER_GROUPINGS AS (
SELECT 'HIERARCHY' AS HIERARCHY,'CUSTOMER' AS CUSTOMER,'PRIORITY' AS PRIORITY FROM DUAL UNION ALL
SELECT '58007310' AS HIERARCHY,'AMAZON' AS CUSTOMER,'TIER 1' AS PRIORITY FROM DUAL UNION ALL
SELECT '58064480' AS HIERARCHY,'AMAZON' AS CUSTOMER,'TIER 1' AS PRIORITY FROM DUAL UNION ALL
SELECT '58059586' AS HIERARCHY,'AMAZON' AS CUSTOMER,'TIER 1' AS PRIORITY FROM DUAL UNION ALL
SELECT '58006486' AS HIERARCHY,'AWG' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58006496' AS HIERARCHY,'AWG' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58008423' AS HIERARCHY,'BIG LOTS' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58006900' AS HIERARCHY,'BJS WHOLESALE' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58006151' AS HIERARCHY,'BOZZUTOS' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58015287' AS HIERARCHY,'BRADY INDUSTRIES' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58013906' AS HIERARCHY,'BUNZL' AS CUSTOMER,'TIER 1' AS PRIORITY FROM DUAL UNION ALL
SELECT '58019996' AS HIERARCHY,'BUNZL' AS CUSTOMER,'TIER 1' AS PRIORITY FROM DUAL UNION ALL
SELECT '58006032' AS HIERARCHY,'C AND S' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58004966' AS HIERARCHY,'COSTCO' AS CUSTOMER,'TIER 1' AS PRIORITY FROM DUAL UNION ALL
SELECT '58003496' AS HIERARCHY,'CVS' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58007089' AS HIERARCHY,'DOLLAR GENERAL' AS CUSTOMER,'TIER 1' AS PRIORITY FROM DUAL UNION ALL
SELECT '58062902' AS HIERARCHY,'ESSENDANT' AS CUSTOMER,'TIER 1' AS PRIORITY FROM DUAL UNION ALL
SELECT '58007093' AS HIERARCHY,'FAMILY DOLLAR' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58013436' AS HIERARCHY,'GENERAL KCP' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58006193' AS HIERARCHY,'GIANT EAGLE' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58006415' AS HIERARCHY,'HARRIS TEETER' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58006843' AS HIERARCHY,'HEBUTT' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58063328' AS HIERARCHY,'JET.COM' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58056571' AS HIERARCHY,'KC DE MEXICO' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58004860' AS HIERARCHY,'KROGER' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58004944' AS HIERARCHY,'MARCS DISTRIBUTION' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58011420' AS HIERARCHY,'MCKESSON' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58004894' AS HIERARCHY,'MEIJER' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58017333' AS HIERARCHY,'MENARDS' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58006857' AS HIERARCHY,'PUBLIX' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58007101' AS HIERARCHY,'RITEAID' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58006864' AS HIERARCHY,'SAFEWAY' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58005988' AS HIERARCHY,'SAMS' AS CUSTOMER,'TIER 1' AS PRIORITY FROM DUAL UNION ALL
SELECT '58006511' AS HIERARCHY,'SHOPKO' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58060619' AS HIERARCHY,'SP RICHARDS' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58018975' AS HIERARCHY,'STAPLES' AS CUSTOMER,'TIER 1' AS PRIORITY FROM DUAL UNION ALL
SELECT '58020701' AS HIERARCHY,'STAPLES' AS CUSTOMER,'TIER 1' AS PRIORITY FROM DUAL UNION ALL
SELECT '58006054' AS HIERARCHY,'SUPERVALUE' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58003411' AS HIERARCHY,'TARGET' AS CUSTOMER,'TIER 1' AS PRIORITY FROM DUAL UNION ALL
SELECT '58015593' AS HIERARCHY,'US FOOD SERVICE' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58015837' AS HIERARCHY,'VERITIV' AS CUSTOMER,'TIER 1' AS PRIORITY FROM DUAL UNION ALL
SELECT '58015716' AS HIERARCHY,'VERITIV' AS CUSTOMER,'TIER 1' AS PRIORITY FROM DUAL UNION ALL
SELECT '58004948' AS HIERARCHY,'WAKEFERN' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58007162' AS HIERARCHY,'WALGREENS' AS CUSTOMER,'' AS PRIORITY FROM DUAL UNION ALL
SELECT '58005914' AS HIERARCHY,'WALMART' AS CUSTOMER,'TIER 1' AS PRIORITY FROM DUAL UNION ALL
SELECT '58014837' AS HIERARCHY,'WAXIE' AS CUSTOMER,'' AS PRIORITY FROM DUAL
),
/********************************************************************************************************************
/* REASON CODE DESCRIPTION LIST - COPY DESCRIPTIONS FOR ALL CODES AS D- AND P- CODES
/********************************************************************************************************************/
REASON_CODE_DESC AS (
SELECT REASON_CODE, MIN(TM_DESC) AS "REASON_DESC" FROM ABPP_REASON_CODE_SCORE GROUP BY REASON_CODE
UNION ALL SELECT 'D-' || REASON_CODE, MIN(TM_DESC) AS "REASON_DESC" FROM ABPP_REASON_CODE_SCORE GROUP BY REASON_CODE
UNION ALL SELECT 'P-' || REASON_CODE, MIN(TM_DESC) AS "REASON_DESC" FROM ABPP_REASON_CODE_SCORE GROUP BY REASON_CODE),
/********************************************************************************************************************
/* SALES ORG WITH THE MOST CUBIC VOLUME ON EACH LOAD
/********************************************************************************************************************/
SALES_ORG AS (
SELECT LD_LEG_ID, RFRC_NUM10 AS "SALES_ORG" 
    FROM (
    SELECT LL.LD_LEG_ID, SH.RFRC_NUM10, sum(SH.BS_VOL), ROW_NUMBER() OVER (PARTITION BY LL.LD_LEG_ID ORDER BY sum(SH.BS_VOL) desc) AS ROW_NBR
    FROM LOAD_LEG_R LL
    JOIN LOAD_LEG_DETAIL_R LLD ON LL.LD_LEG_ID = LLD.LD_LEG_ID
    JOIN SHIPMENT_R SH ON LLD.SHPM_ID = SH.SHPM_ID
    GROUP BY LL.LD_LEG_ID, SH.RFRC_NUM10)
WHERE ROW_NBR = 1
),
/********************************************************************************************************************
/* FIRST TENDER RESPONSE 
/********************************************************************************************************************/
FIRST_TENDER AS(
SELECT LD_LEG_ID, CARR_CD, SRVC_CD, FTA_CNT, CRTD_DTT AS "TDR_DTT", ROUND((STRD_DTT-CRTD_DTT) * 24,1) AS "TDR_LEAD_HRS"
FROM (SELECT TRT.*,
CASE WHEN RSPS_SEC_CD = 'ACPD' THEN 1 ELSE 0 END AS "FTA_CNT",
ROW_NUMBER() OVER (PARTITION BY TRT.LD_LEG_ID ORDER BY TRT.TDR_REQ_ID) AS ROW_NBR 
FROM TDR_REQ_T TRT) 
WHERE ROW_NBR = 1),
/********************************************************************************************************************
/* LOAD ON-TIME DELIVERY SERVICE PERFORMANCE - THIS IS AGGREGATED.  A MULT-STOP DELIVERY WILL BE REFLECTED AS 1 LOAD
/********************************************************************************************************************/
LOAD_OTD_SERVICE AS (SELECT LOAD_ID, TEAM_NAME, TEAM_GROUP, MAX(BASE_APPOINTMENT_DATETIME) AS "LAST_STOP_BASE_APPT_DATETIME", MAX(FINAL_APPOINTMENT_DATETIME) AS "LAST_STOP_FINAL_APPT_DATETIME",
  MAX(ARRIVED_AT_DATETIME) AS "LAST_STOP_ACTUAL_ARRIVAL",
  CASE WHEN MAX(CAPS_LATE) = 'Y' THEN 0 ELSE 1 END AS "CAPS_ONTIME_CNT",
  MIN(CAPS_REASON) AS "CAPS_REASON_CD",
  CASE WHEN MAX(CSRS_LATE) = 'Y' THEN 0 ELSE 1 END AS "CSRS_ONTIME_CNT",
  MIN(CSRS_REASON) AS "CSRS_REASON_CD",
  COUNT(LOAD_ID) AS STOP_CNT,
  SUM(CASE WHEN ARRIVED_AT_DATETIME IS NOT NULL AND CAPS_REASON <> 'MEFC' THEN 1 ELSE 0 END) AS "STOP_RESPONSE_CNT",
  SUM(CASE WHEN ARRIVED_AT_DATETIME IS NOT NULL AND CAPS_LATE = 'N' THEN 1 ELSE 0 END) AS "CAPS_ONTIME_STOP_CNT",
  SUM(CASE WHEN ARRIVED_AT_DATETIME IS NOT NULL AND CSRS_LATE = 'N' THEN 1 ELSE 0 END) AS "CSRS_ONTIME_STOP_CNT"
FROM ABPP_OTC_CAPS_MASTER WHERE STOP_NUM > 1 GROUP BY LOAD_ID,TEAM_NAME,TEAM_GROUP),
/********************************************************************************************************************
/* GET PICK LOCATION AND ACTUAL PICK TIME FROM CAPS WHEN IT EXISTS 
/********************************************************************************************************************/
CAPS_PICK_STOPS AS (
SELECT LOAD_ID, LOCATION_NUM AS "PICK_LOCATION_ID", BASE_APPOINTMENT_DATETIME AS "PICK_APPOINTMENT_DATETIME", DEPARTED_DATETIME AS "CARR_DEPARTED_PICK_DATETIME", TEAM_NAME, TEAM_GROUP
FROM ABPP_OTC_CAPS_MASTER WHERE STOP_NUM =1
),
/********************************************************************************************************************
/* GET BASE AND FINAL APPOINTMENTS FROM THE FIRST DROP STOP
/********************************************************************************************************************/
CAPS_FIRST_DROP_STOPS AS (
SELECT LOAD_ID, BASE_APPOINTMENT_DATETIME AS "DROP_APPOINTMENT_DATETIME", ARRIVED_AT_DATETIME AS "CARR_ARRIVE_FRST_DROP_DATE"
FROM ABPP_OTC_CAPS_MASTER WHERE STOP_NUM =2
),
/********************************************************************************************************************
/* GET THE DISTANCE TO FIRST DROP STOP PLUS CURRENT APPOINTMENT 
/********************************************************************************************************************/
DIST_TO_FIRST_DROP AS (
SELECT SR.LD_LEG_ID, SR.FRMPREVSTOP_DIST, AR.APT_FRM_DTT AS "CURRENT_FRMAPT_DATETIME", AR.APT_TO_DTT AS "CURRENT_TOAPT_DATETIME", AD.CTY_NAME, AD.STA_CD
FROM STOP_R SR 
JOIN APPOINTMENT_R AR ON SR.APT_ID=AR.APT_ID 
JOIN ADDRESS_R AD ON AD.ADDR_ID = SR.ADDR_ID
WHERE SEQ_NUM = 2
)
/********************************************************************************************************************
/* METRICS QUERY
/********************************************************************************************************************/
SELECT 
LLR.LD_LEG_ID,
SO.SALES_ORG,
STAT.STAT_SHRT_DESC AS "LOAD_STATUS",
LLR.CARR_CD,
LLR.SRVC_CD,
LLR.EQMT_TYP,
 CASE WHEN llr.eqmt_typ = '53IM' THEN
            'INTERMODAL'
        ELSE
            'TRUCK'
    END AS shipmode,
CASE
    WHEN SUBSTR(LLR.FRST_SHPG_LOC_CD,5,1) = '-' AND SUBSTR(LLR.LAST_SHPG_LOC_CD,5,1) = '-' THEN 'STO'
    WHEN SUBSTR(LLR.FRST_SHPG_LOC_CD,5,1) = '-' AND SUBSTR(LLR.LAST_SHPG_LOC_CD,1,1) = '5' THEN 'CUSTOMER'
    WHEN SUBSTR(LLR.FRST_SHPG_LOC_CD,5,1) = '-' AND LLR.LAST_SHPG_LOC_CD = '99999999' THEN 'CUSTOMER'
    WHEN SUBSTR(LLR.FRST_SHPG_LOC_CD,1,1) = 'V' AND SUBSTR(LAR.CORP1_ID,1,2) = 'RM' THEN 'MATERIALS'
    WHEN SUBSTR(LLR.FRST_SHPG_LOC_CD,1,1) = 'V' AND SUBSTR(LAR.CORP1_ID,1,2) = 'RF' THEN 'RECFIBER'
    ELSE 'UNKNOWN'
END AS "SHIP_TYPE",
( CASE 
                    WHEN( Substr(llr.frst_shpg_loc_name, 1, 2) = 'RF' ) THEN 
                    'RF-INBOUND' 
                    WHEN( Substr(llr.frst_shpg_loc_name, 1, 2) = 'RM' ) THEN 
                    'RM-INBOUND' 
                    WHEN( Substr(llr.last_shpg_loc_cd, 1, 1) = 'R' ) THEN 'RETURNS' 
                    WHEN( Substr(llr.last_shpg_loc_cd, 1, 1) = '1' ) THEN 'INTERMILL' 
                    WHEN( Substr(llr.last_shpg_loc_cd, 1, 1) = '2' ) THEN 'INTERMILL' 
                    ELSE 'CUSTOMER' 
                  END ) 
                AS OrderType,
CASE 
                  WHEN Substr(llr.last_shpg_loc_cd, 1, 4) IN ( 
                       '2000', '2019', '2022', '2023', 
                       '2024', '2026', '2027', '2028', 
                       '2029', '2031', '2032', '2035', 
                       '2036', '2038', '2041', '2049', 
                       '2050', '2054', '2063', '2075', 
                       '2094', '2100', '2137', '2138', 
                       '2142', '2170', '2171', '2172', 
                       '2183', '2187', '2191', '2197', 
                       '2210', '2213', '2240', '2275', 
                       '2283', '2291', '2292', '2300', 
                       '2303', '2307', '2314', '2320', 
                       '2331', '2336', '2347', '2353', 
                       '2358', '2359', '2360', '2369', 
                       '2370', '2385', '2399', '2408', 
                       '2412', '2414', '2419', '2422', 
                       '2443', '2463', '2483', '2487', 
                       '2489', '2496', '2500', '2510', 
                       '2511', '2822', '2839' ) THEN 
                  'CONSUMER' 
                  WHEN Substr(llr.last_shpg_loc_cd, 1, 4) IN ( 
                       '2034', '2039', '2040', '2042', 
                       '2043', '2044', '2048', '2051', 
                       '2079', '2080', '2091', '2096', 
                       '2099', '2104', '2106', '2111', 
                       '2112', '2113', '2124', '2126', 
                       '2161', '2177', '2200', '2234', 
                       '2299', '2301', '2302', '2304', 
                       '2310', '2323', '2325', '2334', 
                       '2348', '2349', '2350', '2356', 
                       '2362', '2363', '2375', '2386', 
                       '2415', '2416', '2425', '2429', 
                       '2446', '2449', '2459', '2460', 
                       '2467', '2474', '2476', '2477', 
                       '2485', '2495', '2505', '2827', 
                       '2833', '2834', '2837' ) THEN 'KCP' 
                  ELSE '' 
                END 
                BUS_UNIT,                  

LLR.FRST_CTY_NAME || ', ' || LLR.FRST_STA_CD || ' to ' || CASE WHEN LLR.LAST_CTRY_CD = 'USA' THEN SUBSTR(LLR.LAST_PSTL_CD,1,5) ELSE LLR.LAST_CTY_NAME || ', ' || LLR.LAST_STA_CD END AS "LANE_DESC",
CASE 
                  WHEN( Substr(llr.frst_shpg_loc_cd, 1, 1) = 'V' ) THEN 'INBOUND' 
                  ELSE 'OUTBOUND' 
                END 
                AS InboundOutbound,
Cast(Nvl(Substr(llr.FRST_SHPG_LOC_CD, 0, 
                              Instr(llr.FRST_SHPG_LOC_CD, '-') 
                                  - 1), llr.FRST_SHPG_LOC_CD) AS VARCHAR2 
                     (10)) AS 
                frst_shpg_loc_cd_T, 
LLR.FRST_SHPG_LOC_CD,
LLR.FRST_CTY_NAME,
LLR.FRST_STA_CD,
CASE 
  WHEN LLR.FRST_CTRY_CD = 'USA' THEN SUBSTR(LLR.FRST_PSTL_CD,1,5) 
  WHEN LLR.FRST_CTRY_CD = 'CAN' THEN SUBSTR(LLR.FRST_PSTL_CD,1,6)
  ELSE LLR.FRST_PSTL_CD
END AS FRST_ZIP_CD,
LLR.FRST_CTRY_CD,
LLR.LAST_SHPG_LOC_CD,
CASE
    WHEN CUSTOMER_GROUPINGS.CUSTOMER IS NOT NULL THEN CUSTOMER_GROUPINGS.CUSTOMER
    ELSE 
        CASE
            WHEN SUBSTR(LLR.LAST_SHPG_LOC_CD,5,1)='-' THEN 'K-C'
            WHEN SUBSTR(LLR.LAST_SHPG_LOC_CD,1,2)='58' THEN 'OTHER CUSTOMER'
            WHEN SUBSTR(LLR.LAST_SHPG_LOC_CD,5,1)='99999999' THEN 'OTHER CUSTOMER'
            WHEN SUBSTR(LLR.LAST_SHPG_LOC_CD,1,2)='AK' THEN 'HUB'
            WHEN SUBSTR(LLR.LAST_SHPG_LOC_CD,1,2)='HI' THEN 'HUB'
            WHEN SUBSTR(LLR.LAST_SHPG_LOC_CD,1,4)='LCL-' THEN 'HUB'
            ELSE 'UNKNOWN'
        END
END AS "SELL_TO_CUST",
LLR.LAST_CTY_NAME AS "FINAL_CITY_NAME",
LLR.LAST_STA_CD AS "FINAL_STA_CD",
LLR.LAST_CTRY_CD AS "FINAL_CTRY_CD",
CASE 
  WHEN LLR.LAST_CTRY_CD = 'USA' THEN SUBSTR(LLR.LAST_PSTL_CD,1,5) 
  WHEN LLR.LAST_CTRY_CD = 'CAN' THEN SUBSTR(LLR.LAST_PSTL_CD,1,6)
  ELSE LLR.LAST_PSTL_CD
END AS FINAL_ZIP_CD,
DTFD.FRMPREVSTOP_DIST AS "DISTANCE_TO_FRST_STOP",
--ROUND(DTFD.FRMPREVSTOP_DIST / 46,1) AS "DRIVE_HOURS_TO_FRST_STOP",
--CASE 
--    WHEN LLR.EQMT_TYP = '53IM' THEN
--        ROUND((CDS.DROP_APPOINTMENT_DATETIME - CPS.PICK_APPOINTMENT_DATETIME)*24,1)
--    ELSE
--        ROUND((DTFD.FRMPREVSTOP_DIST / 46) + ((FLOOR((DTFD.FRMPREVSTOP_DIST / 46)/11)*11)+2),1)
--END  AS "TRIP_HOURS",
CPS.TEAM_NAME,
CPS.TEAM_GROUP,
LLR.CHGD_AMT_DLR,
TRUNC(FT.TDR_DTT) AS "FRST_TENDER_DATE",
CPS.PICK_APPOINTMENT_DATETIME,
CPS.CARR_DEPARTED_PICK_DATETIME,
CASE WHEN LLR.SHPD_DTT IS NULL THEN TRUNC(CPS.PICK_APPOINTMENT_DATETIME) ELSE LLR.SHPD_DTT END AS SHIP_DATE ,
CASE 
  WHEN LLR.SHPD_DTT IS NULL THEN TO_CHAR(CPS.PICK_APPOINTMENT_DATETIME-1,'D')  || '-' || TO_CHAR(CPS.PICK_APPOINTMENT_DATETIME,'DY') 
  ELSE TO_CHAR(LLR.SHPD_DTT-1,'D')  || '-' || TO_CHAR(LLR.SHPD_DTT,'DY') 
END AS SHIP_DOW,
CASE 
  WHEN LLR.SHPD_DTT IS NULL THEN TRUNC(CPS.PICK_APPOINTMENT_DATETIME,'IW')
  ELSE TRUNC(LLR.SHPD_DTT,'IW')
END AS SHIP_WEEK,
CASE 
  WHEN LLR.SHPD_DTT IS NULL THEN TRUNC(CPS.PICK_APPOINTMENT_DATETIME,'MM')
  ELSE TRUNC(LLR.SHPD_DTT,'MM')
END AS SHIP_MONTH,
--CASE
--    WHEN LLR.EQMT_TYP = '53IM' THEN
--        TRUNC(CPS.PICK_APPOINTMENT_DATETIME) + 1
--    ELSE
--        CDS.DROP_APPOINTMENT_DATETIME - (((DTFD.FRMPREVSTOP_DIST / 46) + ((FLOOR((DTFD.FRMPREVSTOP_DIST / 46)/11)*11)+2))/24)
--END AS "DROP_DEAD_PICK_DATETIME",
--CDS.DROP_APPOINTMENT_DATETIME AS "FRST_STOP_BASE_APPT_DATETIME",
LOS.LAST_STOP_BASE_APPT_DATETIME,
LOS.LAST_STOP_FINAL_APPT_DATETIME,
TO_CHAR(LOS.LAST_STOP_FINAL_APPT_DATETIME-1,'D')  || '-' || TO_CHAR(LOS.LAST_STOP_FINAL_APPT_DATETIME,'DY') AS FINAL_APPT_DOW,
TRUNC(LOS.LAST_STOP_FINAL_APPT_DATETIME,'IW') AS FINAL_APPT_WEEK,
TRUNC(LOS.LAST_STOP_FINAL_APPT_DATETIME,'MM') AS FINAL_APPT_MONTH,
TRUNC(LOS.LAST_STOP_ACTUAL_ARRIVAL) AS "ACTUAL_DELIVERY_DATE",
TO_CHAR(LOS.LAST_STOP_ACTUAL_ARRIVAL-1,'D')  || '-' || TO_CHAR(LOS.LAST_STOP_ACTUAL_ARRIVAL,'DY') AS ACTUAL_DELIVERY_DOW,
TRUNC(LOS.LAST_STOP_ACTUAL_ARRIVAL,'IW') AS ACTUAL_DELIVERY_WEEK,
TRUNC(LOS.LAST_STOP_ACTUAL_ARRIVAL,'MM') AS ACTUAL_DELIVERY_MONTH,
LLR.MILE_DIST AS "TOTAL_MILES",
1 AS "LOAD_COUNT",
LOS.STOP_CNT AS "STOP_COUNT",
LOS.STOP_RESPONSE_CNT AS "STOP_RESPONSE_COUNT",
FT.FTA_CNT,
FT.TDR_LEAD_HRS,
CASE 
  WHEN LLR.EQMT_TYP = '53IM' THEN
    CASE 
      WHEN CPS.CARR_DEPARTED_PICK_DATETIME IS NULL AND SYSDATE > TRUNC(CPS.PICK_APPOINTMENT_DATETIME) + 1 THEN 0 
      WHEN CPS.CARR_DEPARTED_PICK_DATETIME IS NULL AND SYSDATE <= TRUNC(CPS.PICK_APPOINTMENT_DATETIME) + 1 THEN 1 
      WHEN CPS.CARR_DEPARTED_PICK_DATETIME IS NOT NULL AND CPS.CARR_DEPARTED_PICK_DATETIME > TRUNC(CPS.PICK_APPOINTMENT_DATETIME) + 1 THEN 0 
      ELSE 1 
    END
  ELSE
    CASE 
      WHEN CPS.CARR_DEPARTED_PICK_DATETIME IS NULL AND SYSDATE > CDS.DROP_APPOINTMENT_DATETIME - (((DTFD.FRMPREVSTOP_DIST / 46) + ((FLOOR((DTFD.FRMPREVSTOP_DIST / 46)/11)*11)+2))/24) THEN 0 
      WHEN CPS.CARR_DEPARTED_PICK_DATETIME IS NULL AND SYSDATE <= CDS.DROP_APPOINTMENT_DATETIME - (((DTFD.FRMPREVSTOP_DIST / 46) + ((FLOOR((DTFD.FRMPREVSTOP_DIST / 46)/11)*11)+2))/24) THEN 1 
      WHEN CPS.CARR_DEPARTED_PICK_DATETIME IS NOT NULL AND CPS.CARR_DEPARTED_PICK_DATETIME > CDS.DROP_APPOINTMENT_DATETIME - (((DTFD.FRMPREVSTOP_DIST / 46) + ((FLOOR((DTFD.FRMPREVSTOP_DIST / 46)/11)*11)+2))/24) THEN 0 
      ELSE 1 
    END
END AS "CAPS_OTP_CNT",
LOS.CAPS_ONTIME_CNT AS "CAPS_OTD_CNT",
LOS.CAPS_ONTIME_STOP_CNT AS "CAPS_OTD_STOP_CNT",
CASE WHEN RSD1.REASON_DESC IS NULL THEN LOS.CAPS_REASON_CD ELSE RSD1.REASON_DESC END AS "CAPS_REASON_DESC",
LOS.CSRS_ONTIME_CNT AS "CSRS_OTD_CNT",
LOS.CSRS_ONTIME_STOP_CNT AS "CSRS_OTD_STOP_CNT",
CASE WHEN RSD2.REASON_DESC IS NULL THEN LOS.CSRS_REASON_CD ELSE RSD2.REASON_DESC END AS "CSRS_REASON_DESC",
TRUNC(SYSDATE, 'MI') AS "LAST_REFRESHED_TIME"
FROM 
LOAD_LEG_R LLR
JOIN LOAD_AT_R LAR ON LLR.FRST_SHPG_LOC_CD = LAR.SHPG_LOC_CD 
JOIN STATUS_R STAT ON LLR.CUR_OPTLSTAT_ID = STAT.STAT_ID  
JOIN CAPS_PICK_STOPS CPS ON CPS.LOAD_ID=LLR.LD_LEG_ID
JOIN CAPS_FIRST_DROP_STOPS CDS ON CDS.LOAD_ID=LLR.LD_LEG_ID
JOIN LOAD_OTD_SERVICE LOS ON LOS.LOAD_ID = LLR.LD_LEG_ID
JOIN FIRST_TENDER FT ON FT.LD_LEG_ID = LLR.LD_LEG_ID
JOIN DIST_TO_FIRST_DROP DTFD ON DTFD.LD_LEG_ID = LLR.LD_LEG_ID 
JOIN SALES_ORG SO ON SO.LD_LEG_ID = LLR.LD_LEG_ID
LEFT OUTER JOIN CUSTOMER_GROUPINGS ON CUSTOMER_GROUPINGS.HIERARCHY = SUBSTR(LLR.LAST_SHPG_LOC_CD,1,8)
LEFT OUTER JOIN REASON_CODE_DESC RSD1 ON LOS.CAPS_REASON_CD = RSD1.REASON_CODE
LEFT OUTER JOIN REASON_CODE_DESC RSD2 ON LOS.CSRS_REASON_CD = RSD2.REASON_CODE
WHERE
LLR.CUR_OPTLSTAT_ID BETWEEN 315 AND 350 AND
LLR.EQMT_TYP IN ('48FT','53FT','53IM','53RT','53TC','53HC')