SELECT * FROM OPENQUERY(NAJDAPRD,'WITH
/*
GET THE APPOINTMENT REQUIREMENTS VS MADE FOR EACH SHIPMENT
*/
APPT_REQ AS (SELECT 
SR.SHPM_ID,
SUM(CASE WHEN LLDR.DROP_APT_RQRD_YN = ''Y'' THEN 1 ELSE 0 END) AS APPT_RQRD_CNT,
SUM(CASE WHEN AR.CUR_STAT_ID = 615 THEN 1 ELSE 0 END) AS APPT_MADE_CNT,
MIN(ST.STAT_SHRT_DESC) AS APPT_STATUS
FROM NAJDAADM.SHIPMENT_R SR
JOIN NAJDAADM.LOAD_LEG_DETAIL_R LLDR ON LLDR.SHPM_ID = SR.SHPM_ID
LEFT OUTER JOIN NAJDAADM.APPOINTMENT_R AR ON AR.APT_ID = LLDR.DROP_APT_ID
LEFT OUTER JOIN NAJDAADM.STATUS_R ST ON ST.STAT_ID = AR.CUR_STAT_ID
GROUP BY SR.SHPM_ID
)/*,

 GET THE CURRENT LOAD STATUS DESCRIPTION

LOAD_STATUS AS (
 SELECT LLR.LD_LEG_ID, ST.STAT_SHRT_DESC AS LOAD_STATUS
 FROM NAJDAADM.LOAD_LEG_R LLR
 JOIN NAJDAADM.STATUS_R ST ON ST.STAT_ID=LLR.CUR_OPTLSTAT_ID
)*/
/*
 SHIPMENT QUERY TO CAPTURE RELEVANT SHIPMENT COLUMNS AND CALCULATIONS
*/
SELECT  
SR.SHPM_NUM,
ST.STAT_SHRT_DESC AS ORDER_STATUS,
ST1.STAT_SHRT_DESC AS LOAD_STATUS,
SR.CRTD_DTT,
TRUNC(SR.CRTD_DTT) AS CRTD_DT,
TRUNC(SR.FRM_PKUP_DTT) AS MAD_DT, 
TRUNC(SR.FRM_DLVY_DTT) AS RDD_DT,
SR.BS_VOL,
SR.BS_WGT,
SR.HOLD_YN,
SR.SPTO_APT_RQRD_YN,
AR.APPT_RQRD_CNT,
AR.APPT_MADE_CNT,
AR.APPT_STATUS,
SR.PLAN_ID,
SR.SHPM_DESC AS DELIVERY_NUM,
SR.FRM_SHPG_LOC_CD,
SR.FRM_NAME,
SR.FRM_CTY_NAME,
SR.FRM_STA_CD,
CASE 
  WHEN SR.FRM_CTRY_CD = ''USA'' THEN SUBSTR(SR.FRM_PSTL_CD,1,5) 
  WHEN SR.FRM_CTRY_CD = ''CAN'' THEN SUBSTR(SR.FRM_PSTL_CD,1,6)
  ELSE SR.FRM_PSTL_CD
END AS FRM_PSTL_CD,
SR.FRM_CTRY_CD,
SR.TO_SHPG_LOC_CD,
SUBSTR(SR.TO_SHPG_LOC_CD,1,8) AS H2_ID,
SR.TO_NAME,
SR.TO_CTY_NAME,
SR.TO_STA_CD,
CASE 
  WHEN SR.TO_CTRY_CD = ''USA'' THEN SUBSTR(SR.TO_PSTL_CD,1,5) 
  WHEN SR.TO_CTRY_CD = ''CAN'' THEN SUBSTR(SR.TO_PSTL_CD,1,6)
  ELSE SR.TO_PSTL_CD
END AS TO_PSTL_CD,
SR.TO_CTRY_CD,
SR.PLAN_COUNT,
SR.TENDER_COUNT,
SR.TDRACPT_COUNT,
SR.CFMG_COUNT,
CASE
    WHEN SR.FRM_CTRY_CD NOT IN (''USA'',''CAN'',''MEX'') THEN ''IMPORT''
    WHEN SR.TO_CTRY_CD NOT IN (''USA'',''CAN'',''MEX'') THEN ''EXPORT''
    WHEN SUBSTR(SR.FRM_SHPG_LOC_CD,5,1) = ''-'' AND SUBSTR(SR.TO_SHPG_LOC_CD,5,1) = ''-'' THEN ''STO'' 
    WHEN SUBSTR(SR.FRM_SHPG_LOC_CD,5,1) = ''-'' AND SUBSTR(SR.TO_SHPG_LOC_CD,1,1) = ''5'' THEN ''CUSTOMER''
    WHEN SUBSTR(SR.FRM_SHPG_LOC_CD,5,1) = ''-'' AND SR.TO_SHPG_LOC_CD = ''99999999'' THEN ''CUSTOMER''
    WHEN SUBSTR(SR.FRM_SHPG_LOC_CD,1,1) = ''V'' AND SUBSTR(LAR.CORP1_ID,1,2) = ''RM'' THEN ''MATERIALS''
    WHEN SUBSTR(SR.TO_SHPG_LOC_CD,1,1) = ''V'' AND SUBSTR(LAR.CORP1_ID,1,2) = ''RF'' THEN ''RECFIBER''
    ELSE ''UNKNOWN''
END AS SHIP_TYPE,
SR.RFRC_NUM1 AS SHIP_METHOD,
SR.RFRC_NUM5 AS CUST_PO_NUM,
SR.RFRC_NUM8 AS CSR_NAME,
SR.RFRC_NUM10 AS SALES_ORG,
CASE    WHEN SR.RFRC_NUM10 IN (''2810'',''2820'',''Z01'') THEN ''KCNA''
        WHEN SR.RFRC_NUM10 IN (''2811'',''2821'',''Z02'',''Z04'',''Z06'',''Z07'') THEN ''KCP'' 
        WHEN SR.RFRC_NUM10 = ''Z05'' THEN CAR.CORP1_ID
        WHEN SR.RFRC_NUM10 IS NULL AND SUBSTR(LAR.CORP1_ID,1,2) = ''RF'' THEN ''KCP'' 
        WHEN SR.RFRC_NUM10 IS NULL AND SUBSTR(LAR.CORP1_ID,1,2) <> ''RF'' THEN CAR.CORP1_ID
        WHEN SR.RFRC_NUM10 IS NULL AND LAR.CORP1_ID IS NULL THEN CAR.CORP1_ID
END AS BUSINESS_UNIT,
SR.RFRC_NUM11 AS UNLOAD_METHOD,
SR.LD_LEG_ID,
SR.HOLD_SEC_CD
FROM 
NAJDAADM.SHIPMENT_R SR
JOIN NAJDAADM.STATUS_R ST ON ST.STAT_ID = SR.CUR_OPTLSTAT_ID
LEFT JOIN NAJDAADM.LOAD_LEG_R LLR ON llr.LD_LEG_ID = SR.LD_LEG_ID
LEFT JOIN NAJDAADM.STATUS_R ST1 ON ST1.STAT_ID = LLR.CUR_OPTLSTAT_ID
JOIN APPT_REQ AR ON AR.SHPM_ID = SR.SHPM_ID
LEFT OUTER JOIN NAJDAADM.LOAD_AT_R LAR ON SR.FRM_SHPG_LOC_CD = LAR.SHPG_LOC_CD
LEFT OUTER JOIN NAI2PADM.CONSIGNEE_R CAR ON SR.TO_SHPG_LOC_CD = CAR.SHPG_LOC_CD 
/*LEFT OUTER JOIN LOAD_STATUS LS ON LS.LD_LEG_ID = SR.LD_LEG_ID*/
WHERE SR.FRM_PKUP_DTT BETWEEN TRUNC(SYSDATE) - 30 AND TRUNC(SYSDATE) + 120 
AND SR.CUR_OPTLSTAT_ID < 255')data