SELECT ABPP_OTC_CAPS_MASTER.LOAD_ID, a.NAME 
FROM  ABPP_OTC_CAPS_MASTER
LEFT JOIN 
    (
        SELECT NAME, CARR_CD  -- <----- this
        FROM CARRIER_R
    ) AS a
ON ABPP_OTC_CAPS_MASTER.CARRIER_SCAC = a.CARR_CD

SELECT DISTINCT ABPP_OTC_CAPS_MASTER.LOAD_ID, Count(ABPP_OTC_CAPS_MASTER.STOP_NUM) AS CountOfSTOP_NUM
FROM ABPP_OTC_CAPS_MASTER
GROUP BY ABPP_OTC_CAPS_MASTER.LOAD_ID
ORDER BY Count(ABPP_OTC_CAPS_MASTER.STOP_NUM) DESC;

[SHIPMENT]
JOIN ON [SHIPMENT].[LOAD ID] = [LOAD].[LOAD ID]
JOIN ON [SHIPMENT].[LOAD ID] = [LOAD/STOP EVENT].[LOAD ID]
JOIN ON [SHIPMENT].[LOAD ID] = [FREIGHT PAYMENT].[LOAD ID]
JOIN ON [SHIPMENT].[LOAD ID] = [FREIGHT PAYMENT CHARGE TYPE].[LOAD ID]
JOIN ON [SHIPMENT].[LOAD ID] = [CAPS].[LOAD NUMBER]