table Date
	lineageTag: d4e5f6a7-b8c9-0123-def4-567890123456
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey: true
		formatString: Short Date
		lineageTag: d1d1d1d1-d1d1-d1d1-d1d1-d1d1d1d1d1d1
		summarizeBy: none
		sourceColumn: Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: d2d2d2d2-d2d2-d2d2-d2d2-d2d2d2d2d2d2
		summarizeBy: none
		sourceColumn: Year

	column Month
		dataType: int64
		formatString: 0
		lineageTag: d3d3d3d3-d3d3-d3d3-d3d3-d3d3d3d3d3d3
		summarizeBy: none
		sourceColumn: Month

	column MonthName
		dataType: string
		lineageTag: d4d4d4d4-d4d4-d4d4-d4d4-d4d4d4d4d4d4
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

	column Quarter
		dataType: string
		lineageTag: d5d5d5d5-d5d5-d5d5-d5d5-d5d5d5d5d5d5
		summarizeBy: none
		sourceColumn: Quarter

	partition Date = m
		mode: import
		source = ```
			let
			    StartDate = #date(2023, 1, 1),
			    EndDate = #date(2024, 12, 31),
			    
			    DateList = List.Dates(StartDate, Duration.Days(EndDate - StartDate) + 1, #duration(1, 0, 0, 0)),
			    
			    ToTable = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
			    
			    AddYear = Table.AddColumn(ToTable, "Year", each Date.Year([Date]), Int64.Type),
			    AddMonth = Table.AddColumn(AddYear, "Month", each Date.Month([Date]), Int64.Type),
			    AddMonthName = Table.AddColumn(AddMonth, "MonthName", each Date.MonthName([Date]), type text),
			    AddQuarter = Table.AddColumn(AddMonthName, "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date])), type text),
			    
			    TypedTable = Table.TransformColumnTypes(AddQuarter, {{"Date", type date}})
			in
			    TypedTable
			```

