table Products
	lineageTag: b2c3d4e5-f6a7-8901-bcde-f23456789012

	column ProductID
		dataType: int64
		isKey: true
		formatString: 0
		lineageTag: aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
		summarizeBy: none
		sourceColumn: ProductID

	column ProductName
		dataType: string
		lineageTag: bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb
		summarizeBy: none
		sourceColumn: ProductName

	column Category
		dataType: string
		lineageTag: cccccccc-cccc-cccc-cccc-cccccccccccc
		summarizeBy: none
		sourceColumn: Category

	column Weight
		dataType: double
		formatString: #,0.00
		lineageTag: dddddddd-dddd-dddd-dddd-dddddddddddd
		summarizeBy: sum
		sourceColumn: Weight

	column StandardCost
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee
		summarizeBy: sum
		sourceColumn: StandardCost

	partition Products = m
		mode: import
		source = ```
			let
			    Categories = {"Electronics", "Clothing", "Home & Garden", "Sports", "Books"},
			    
			    ProductData = List.Transform(
			        List.Numbers(1, 50, 1),
			        each [
			            ProductID = _,
			            ProductName = "Product " & Text.PadStart(Text.From(_), 3, "0"),
			            Category = Categories{Number.Mod(_ - 1, 5)},
			            Weight = Number.Round(Number.RandomBetween(0.1, 50), 2),
			            StandardCost = Number.Round(Number.RandomBetween(2, 200), 2)
			        ]
			    ),
			    
			    ToTable = Table.FromRecords(ProductData),
			    
			    TypedTable = Table.TransformColumnTypes(ToTable, {
			        {"ProductID", Int64.Type},
			        {"ProductName", type text},
			        {"Category", type text},
			        {"Weight", type number},
			        {"StandardCost", type number}
			    })
			in
			    TypedTable
			```

