DROP TABLE IF EXISTS ##tblChangelogTemp

/*
Create the temp table
*/
CREATE TABLE ##tblChangelogTemp(
LaneID NVARCHAR(20),
Lane NVARCHAR(50),
ChangeType NVARCHAR(20),
ChangeReason NVARCHAR(50),
SCAC NVARCHAR(10),
Field NVARCHAR(10),
PreviousValue NVARCHAR(50),
NewValue NVARCHAR(10),
UpdatedBy NVARCHAR(50),
UpdatedByName NVARCHAR(50),
UpdatedOn Datetime
)

/*
Add the lanes to be deleted
SELECT DISTINCT ChangeType FROM USCTTDEV.dbo.tblBidAppChangelog
SELECT DISTINCT ChangeReason FROM USCTTDEV.dbo.tblBidAppChangelog
SELECT DISTINCT Field FROM USCTTDEV.dbo.tblBidAppChangelog
SELECT * FROM ##tblChangelogTemp

Excel Formula
="SELECT '" & E2 & "' AS Lane, CAST('" & O2 & "' AS NUMERIC(10,2)) AS NewValue, '" & LEFT(B2,4) & "' AS SCAC UNION ALL"
*/
INSERT INTO ##tblChangelogTemp (LaneID,  Lane, ChangeType, ChangeReason, SCAC, Field, PreviousValue, NewValue)
SELECT DISTINCT bar.LaneID,  
change.Lane, 
CASE WHEN bar.[Min Charge] IS NOT NULL THEN 'Rate Level - Flat Chrg' ELSE 'Rate Level - RPM' END,
'Mass Update Rate',
change.SCAC,  
CASE WHEN bar.[Min Charge] IS NOT NULL THEN 'Min Charge' ELSE 'CUR_RPM' END, 
CASE WHEN bar.[Min Charge] IS NOT NULL THEN bar.[Min Charge] ELSE bar.CUR_RPM END,
Change.NewValue
FROM (SELECT 'ALMOBILE-5FL33801' AS Lane, CAST('3' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'ALMOBILE-5IL60543' AS Lane, CAST('1.8' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'ALMOBILE-5MS39401' AS Lane, CAST('5.8' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'ALTHEODO-5OK74037' AS Lane, CAST('2.06' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'FLORLAND-5TN37774' AS Lane, CAST('0.85' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'GAAUGUST-5KY40351' AS Lane, CAST('2.12' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'GAAUGUST-5NJ08016' AS Lane, CAST('2.67' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'GAAUGUST-5NJ08048' AS Lane, CAST('2.66' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'GAAUGUST-5PA18031' AS Lane, CAST('2.75' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'GAAUGUST-5PA18517' AS Lane, CAST('2.8' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'GAAUGUST-5VA24592' AS Lane, CAST('2.75' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'GAMCDONO-5NJ08831' AS Lane, CAST('2.54' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'NCWINSTO-5TN37774' AS Lane, CAST('2.32' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'SCBEECIS-5NJ08016' AS Lane, CAST('2.67' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'SCBEECIS-5NJ08048' AS Lane, CAST('2.67' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'SCBEECIS-5PA18031' AS Lane, CAST('2.75' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'TNLOUDON-5AL36582' AS Lane, CAST('1.93' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'ARCONWAY-5MS38751' AS Lane, CAST('3.34' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'OKJENKS-5KY40223' AS Lane, CAST('1.85' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'OKJENKS-5KY40351' AS Lane, CAST('1.85' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'TXPARIS-5CA93257' AS Lane, CAST('1.52' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'TXPARIS-5IA52641' AS Lane, CAST('1.46' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'TXPARIS-5IL60543' AS Lane, CAST('1.33' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'TXPARIS-5WI53916' AS Lane, CAST('1.34' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'NYELBRID-5AR72032' AS Lane, CAST('1.37' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'WIAPPLET-5MS38834' AS Lane, CAST('1.96' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'ARCONWAY-5TX75605' AS Lane, CAST('3.78' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'ARCONWAY-5TX76177' AS Lane, CAST('2.75' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'ARCONWAY-5TX77474' AS Lane, CAST('2.59' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'OKJENKS-5TX75119' AS Lane, CAST('2.53' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'OKJENKS-5TX76065' AS Lane, CAST('2.55' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'TXPARIS-5MO65559' AS Lane, CAST('1.38' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'TXPARIS-5MS39401' AS Lane, CAST('1.94' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'TXPARIS-5NH03077' AS Lane, CAST('2.09' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'TXPARIS-5OK73533' AS Lane, CAST('4.93' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'TXPARIS-5TX77535' AS Lane, CAST('2.05' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'ARCONWAY-5TX75236' AS Lane, CAST('2.65' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'ARMAUMEL-5WI54303' AS Lane, CAST('2' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'OKJENKS-5TX75236' AS Lane, CAST('2.52' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'TXPARIS-5GA30253' AS Lane, CAST('1.63' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'TXPARIS-5IL60446' AS Lane, CAST('1.33' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'GALAGRAN-5TX75460' AS Lane, CAST('1.71' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC UNION ALL
SELECT 'NCMOCKSV-5TX75460' AS Lane, CAST('1.85' AS NUMERIC(10,2)) AS NewValue, 'SCNN' AS SCAC
) change
LEFT JOIN USCTTDEV.dbo.tblBidAppRatesRFP2021 bar ON bar.Lane = change.Lane
AND bar.SCAC = change.SCAC
ORDER BY bar.LaneID ASC

/*
Remove from changelog temp where the LaneID does not exist
SELECT * FROM ##tblChangelogTemp WHERE LaneID IS NULL
*/
DELETE FROM ##tblChangelogTemp WHERE LaneID IS NULL

/*
Update Lane Level Deletions text
SELECT DISTINCT UpdatedBy, UpdatedByName, MAX(UpdatedOn) AS MaxUpdated
FROM USCTTDEV.dbo.tblBidAppChangelog
GROUP BY UpdatedBy, UpdatedByName
ORDER BY MAX(UpdatedOn) DESC
*/
UPDATE ##tblChangelogTemp
SET 
UpdatedBy = 'B73503',
UpdatedByName = 'Scottie Carpenter',
UpdatedOn = GETDATE()

/*
Update Bid App Rates with new rate info
SELECT * FROM ##tblChangelogTemp
SELECT * INTO ##tblBidAppRatesTemp FROM USCTTDEV.dbo.tblBidAppRatesRFP2021
SELECT * FROM ##tblChangelogTemp WHERE LaneID = 66 AND SCAC = 'HUBG'
SELECT * FROM USCTTDEV.dbo.tblBidAppRatesRFP2021 WHERE LaneID = 66 AND SCAC = 'HUBG'
*/
UPDATE USCTTDEV.dbo.tblBidAppRatesRFP2021
SET CUR_RPM = CASE WHEN cl.ChangeType = 'Rate Level - RPM' THEN cl.NewValue ELSE bar.CUR_RPM END,
[Min Charge] = CASE WHEN cl.ChangeType = 'Rate Level - Flat Chrg' THEN cl.NewValue ELSE bar.[Min Charge] END
FROM USCTTDEV.dbo.tblBidAppRatesRFP2021 bar
INNER JOIN ##tblChangelogTemp cl ON cl.LaneID = bar.LaneID
AND cl.SCAC = bar.SCAC

/*
Insert changes into changelog
DELETE FROM USCTTDEV.dbo.tblBidAppChangelog WHERE UpdatedOn = '2020-12-11 08:25:01.877'
*/
INSERT INTO USCTTDEV.dbo.tblBIdAppChangelog(LaneID, Lane, ChangeType, ChangeReason, SCAC, Field, PreviousValue, NewValue, UpdatedBy, UpdatedByName, UpdatedOn, ChangeTable)
SELECT clt.LaneID,
clt.Lane,
clt.ChangeType, 
clt.ChangeReason,
clt.SCAC,
clt.Field,
clt.PreviousValue,
clt.NewValue,
clt.UpdatedBy,
clt.UpdatedByName,
clt.UpdatedOn,
'tblBidAppRatesRFP2021'
FROM ##tblChangelogTemp clt
LEFT JOIN USCTTDEV.dbo.tblBIdAppChangelog cl ON clt.LaneID = cl.LaneID
AND cl.SCAC = clt.SCAC
AND CAST(cl.UpdatedOn AS DATE) = CAST(clt.UpdatedOn AS DATE)
WHERE cl.LaneID IS NULL
AND cl.SCAC IS NULL
ORDER BY clt.LaneID ASC, clt.SCAC ASC

EXEC USCTTDEV.dbo.sp_AwardWeightedAveragesRFP

EXEC USCTTDEV.dbo.sp_BidAppRatesRank
