/*
This SQL file replicates Tim Zoppa's SQL file, and records historical data to MSSQL since Oracle purges after 90 days
MSSQL AUTHOR: Steve Wolfe
ORACLE AUTHOR: Tim Zoppa
*/

/*
Delete Temp table, if exists
*/
DROP TABLE IF EXISTS
##tblOperationalMetricsTemp

/*
Declare query variable, since query is more than 8,000 characters
*/
DECLARE @myQuery VARCHAR(MAX)

/*
Set query
*/
SET @myQuery = 'WITH
/********************************************************************************************************************
/* MANUAL CUSTOMER GROUPINGS - Updated 9/3/2019
/********************************************************************************************************************/
CUSTOMER_GROUPINGS AS (
SELECT ''HIERARCHY'' AS HIERARCHY,''CUSTOMER'' AS CUSTOMER,''PRIORITY'' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58019941'' AS HIERARCHY,''ACKLAND GRAINGER INC'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006364'' AS HIERARCHY,''AFFILIATED FOODS'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58007310'' AS HIERARCHY,''AMAZON'' AS CUSTOMER,''TIER 1'' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58064480'' AS HIERARCHY,''AMAZON'' AS CUSTOMER,''TIER 1'' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58059586'' AS HIERARCHY,''AMAZON'' AS CUSTOMER,''TIER 1'' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006207'' AS HIERARCHY,''AMERISOURCEBERGEN'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006547'' AS HIERARCHY,''ASSOCIATED FOOD'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58016124'' AS HIERARCHY,''AUTO ZONE'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006486'' AS HIERARCHY,''AWG'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006496'' AS HIERARCHY,''AWG'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58008423'' AS HIERARCHY,''BIG LOTS'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006634'' AS HIERARCHY,''BI-MART CORP'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006900'' AS HIERARCHY,''BJS WHOLESALE'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006151'' AS HIERARCHY,''BOZZUTOS'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58015287'' AS HIERARCHY,''BRADY INDUSTRIES'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006446'' AS HIERARCHY,''BROOKSHIRE GROCERY CO'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58013906'' AS HIERARCHY,''BUNZL'' AS CUSTOMER,''TIER 1'' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58019996'' AS HIERARCHY,''BUNZL'' AS CUSTOMER,''TIER 1'' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006032'' AS HIERARCHY,''C AND S'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58063443'' AS HIERARCHY,''C AND S'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58063454'' AS HIERARCHY,''C AND S'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006478'' AS HIERARCHY,''CERTCO INC'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58004966'' AS HIERARCHY,''COSTCO'' AS CUSTOMER,''TIER 1'' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58003496'' AS HIERARCHY,''CVS'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006201'' AS HIERARCHY,''DELHAIZE'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006878'' AS HIERARCHY,''DELHAIZE'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006155'' AS HIERARCHY,''DEMOULAS'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58064822'' AS HIERARCHY,''DIAPER BANKS'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006763'' AS HIERARCHY,''DISCOUNT DRUG MART'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58007089'' AS HIERARCHY,''DOLLAR GENERAL'' AS CUSTOMER,''TIER 1'' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58013949'' AS HIERARCHY,''DUNKIN DONUTS'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58062902'' AS HIERARCHY,''ESSENDANT'' AS CUSTOMER,''TIER 1'' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006254'' AS HIERARCHY,''FAMILY DOLLAR / DOLLAR TREE'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58007093'' AS HIERARCHY,''FAMILY DOLLAR / DOLLAR TREE'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58008762'' AS HIERARCHY,''FAMILI-PRIX INC'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006775'' AS HIERARCHY,''FAREWAY STORES'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58003605'' AS HIERARCHY,''FEDERATED CO-OP'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58020237'' AS HIERARCHY,''FISHER SCIENTIFIC'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006572'' AS HIERARCHY,''FOOD 4 LESS'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006332'' AS HIERARCHY,''FOOD CITY'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58056179'' AS HIERARCHY,''FRITO LAY'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58013436'' AS HIERARCHY,''GENERAL KCP'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006193'' AS HIERARCHY,''GIANT EAGLE'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006181'' AS HIERARCHY,''GOLUB WHSE'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58008428'' AS HIERARCHY,''GROCERY OUTLET INC'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006415'' AS HIERARCHY,''HARRIS TEETER'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006843'' AS HIERARCHY,''HEBUTT'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006458'' AS HIERARCHY,''HOME DELIVERY INCONTINENCE'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58014425'' AS HIERARCHY,''HOME DEPOT'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006500'' AS HIERARCHY,''HY-VEE'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58063328'' AS HIERARCHY,''JET.COM'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006258'' AS HIERARCHY,''JETRO CASH AND CARRY'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58066013'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58013745'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58015796'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58014239'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58015498'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58011433'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58013729'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58059211'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58019957'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58027580'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58014795'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58027590'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58013894'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58027605'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58015123'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58020259'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58058991'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58020267'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58064604'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58004012'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58011583'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58065128'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58014397'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58015255'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58056525'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58027637'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58005693'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58013832'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58056178'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58011324'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58020059'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58015538'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58065278'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58013681'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58013808'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58014247'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58015462'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58020233'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58020025'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58013653'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58020302'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58015976'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58063481'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58018827'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58011563'' AS HIERARCHY,''KCP CUSTOMER'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58003441'' AS HIERARCHY,''K-MART'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58056571'' AS HIERARCHY,''KC DE MEXICO'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58004860'' AS HIERARCHY,''KROGER'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58003621'' AS HIERARCHY,''LE GROUPE JEAN COUTU INC'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58020277'' AS HIERARCHY,''LOBLAWS'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58003614'' AS HIERARCHY,''LONDON DRUGS'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58064926'' AS HIERARCHY,''MAKRO GROCERS LLC'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58065443'' AS HIERARCHY,''MARCHELEOS INC'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58004944'' AS HIERARCHY,''MARCS DISTRIBUTION'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58011420'' AS HIERARCHY,''MCKESSON'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58011493'' AS HIERARCHY,''MCKESSON'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58011426'' AS HIERARCHY,''MCKESSON'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58004894'' AS HIERARCHY,''MEIJER'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58017333'' AS HIERARCHY,''MENARDS'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58003636'' AS HIERARCHY,''METRO'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58007825'' AS HIERARCHY,''MILLS FLEET FARM'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58009221'' AS HIERARCHY,''MINERS WAREHOUSE'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006296'' AS HIERARCHY,''NASH FINCH'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58064995'' AS HIERARCHY,''OCEAN STATE JOBBERS INC'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58064500'' AS HIERARCHY,''OFFICE DEPOT'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58017541'' AS HIERARCHY,''OZARK AUTO DIST'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006857'' AS HIERARCHY,''PUBLIX'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58007101'' AS HIERARCHY,''RITEAID'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006864'' AS HIERARCHY,''SAFEWAY'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58005988'' AS HIERARCHY,''SAMS'' AS CUSTOMER,''TIER 1'' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006511'' AS HIERARCHY,''SHOPKO'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006527'' AS HIERARCHY,''SCHNUCK MARKETS'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006823'' AS HIERARCHY,''SMART AND FINAL'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58060619'' AS HIERARCHY,''SP RICHARDS'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58018975'' AS HIERARCHY,''STAPLES'' AS CUSTOMER,''TIER 1'' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58020701'' AS HIERARCHY,''STAPLES'' AS CUSTOMER,''TIER 1'' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006815'' AS HIERARCHY,''STATER BROS'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006819'' AS HIERARCHY,''SUPER STORE INDUSTRIES'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006054'' AS HIERARCHY,''SUPERVALUE'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58003411'' AS HIERARCHY,''TARGET'' AS CUSTOMER,''TIER 1'' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58009199'' AS HIERARCHY,''THE NORTH WEST CO'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58015573'' AS HIERARCHY,''ULINE'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58009942'' AS HIERARCHY,''UNITED SALES DISTRIBUTORS'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006638'' AS HIERARCHY,''URM STORES'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58015593'' AS HIERARCHY,''US FOOD SERVICE'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58027733'' AS HIERARCHY,''VA MEDICAL '' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58015837'' AS HIERARCHY,''VERITIV'' AS CUSTOMER,''TIER 1'' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58015716'' AS HIERARCHY,''VERITIV'' AS CUSTOMER,''TIER 1'' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58004948'' AS HIERARCHY,''WAKEFERN'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58007162'' AS HIERARCHY,''WALGREENS'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58005914'' AS HIERARCHY,''WALMART'' AS CUSTOMER,''TIER 1'' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58014837'' AS HIERARCHY,''WAXIE'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006185'' AS HIERARCHY,''WEGMANS FOOD'' AS CUSTOMER,'''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006189'' AS HIERARCHY,''WEIS MARKET'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006807'' AS HIERARCHY,''WINCO FOODS'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL UNION ALL
SELECT ''58006462'' AS HIERARCHY,''WOODMANS'' AS CUSTOMER, '''' AS PRIORITY FROM DUAL
),
/********************************************************************************************************************
/* REASON CODE DESCRIPTION LIST - COPY DESCRIPTIONS FOR ALL CODES AS D- AND P- CODES
/********************************************************************************************************************/
REASON_CODE_DESC AS (
SELECT REASON_CODE, MIN(TM_DESC) AS "REASON_DESC" FROM NAJDATRN.ABPP_REASON_CODE_SCORE GROUP BY REASON_CODE
UNION ALL SELECT ''D-'' || REASON_CODE, MIN(TM_DESC) AS "REASON_DESC" FROM NAJDATRN.ABPP_REASON_CODE_SCORE GROUP BY REASON_CODE
UNION ALL SELECT ''P-'' || REASON_CODE, MIN(TM_DESC) AS "REASON_DESC" FROM NAJDATRN.ABPP_REASON_CODE_SCORE GROUP BY REASON_CODE),
/********************************************************************************************************************
/* SALES ORG WITH THE MOST CUBIC VOLUME ON EACH LOAD
/********************************************************************************************************************/
SALES_ORG AS (
SELECT LD_LEG_ID, RFRC_NUM10 AS "SALES_ORG" 
    FROM (
    SELECT LL.LD_LEG_ID, SH.RFRC_NUM10, sum(SH.BS_VOL), ROW_NUMBER() OVER (PARTITION BY LL.LD_LEG_ID ORDER BY sum(SH.BS_VOL) desc) AS ROW_NBR
    FROM NAJDAADM.LOAD_LEG_R LL
    JOIN NAJDAADM.LOAD_LEG_DETAIL_R LLD ON LL.LD_LEG_ID = LLD.LD_LEG_ID
    JOIN NAJDAADM.SHIPMENT_R SH ON LLD.SHPM_ID = SH.SHPM_ID
    GROUP BY LL.LD_LEG_ID, SH.RFRC_NUM10)
WHERE ROW_NBR = 1
),
/********************************************************************************************************************
/* GET THE FREIGHT TYPE FOR EACH LOAD.  MATERIAL TYPES OF N100 OR NULL ARE CONSIDERED FINISHED GOODS.
/********************************************************************************************************************/
      FREIGHT_TYPE AS (
      SELECT LD_LEG_ID, CASE WHEN RFRC_NUM=''N100'' THEN ''FG'' WHEN RFRC_NUM IS NULL THEN ''FG'' ELSE ''NFG'' END AS "FREIGHT_TYPE" 
           FROM (
          SELECT LL.LD_LEG_ID, RN.RFRC_NUM, ROW_NUMBER() OVER (PARTITION BY LL.LD_LEG_ID ORDER BY RN.RFRC_NUM ASC) AS ROW_NBR
          FROM NAJDAADM.LOAD_LEG_R LL
           JOIN NAJDAADM.LOAD_LEG_DETAIL_R LLD ON LL.LD_LEG_ID = LLD.LD_LEG_ID
           JOIN NAJDAADM.SHIPMENT_R SH ON LLD.SHPM_ID = SH.SHPM_ID
           JOIN NAJDAADM.SHIPMENT_ITEM_R SI ON SH.SHPM_ID = SI.SHPM_ID
            LEFT OUTER JOIN NAJDAADM.REFERENCE_NUMBER_R RN ON SI.SHPM_ITM_ID = RN.SHPM_ITM_ID AND RN.RFRC_NUM_QLFR_ID = 1215)
        WHERE ROW_NBR = 1
        ),
/********************************************************************************************************************
/* FIRST TENDER RESPONSE 
/********************************************************************************************************************/
FIRST_TENDER AS(
SELECT LD_LEG_ID, CARR_CD, SRVC_CD, FTA_CNT, CRTD_DTT AS "TDR_DTT", ROUND((STRD_DTT-CRTD_DTT) * 24,1) AS "TDR_LEAD_HRS"
FROM (SELECT TRT.*,
CASE WHEN RSPS_SEC_CD = ''ACPD'' THEN 1 ELSE 0 END AS "FTA_CNT",
ROW_NUMBER() OVER (PARTITION BY TRT.LD_LEG_ID ORDER BY TRT.TDR_REQ_ID) AS ROW_NBR 
FROM NAJDAADM.TDR_REQ_T TRT) 
WHERE ROW_NBR = 1),
/********************************************************************************************************************
/* LOAD ON-TIME DELIVERY SERVICE PERFORMANCE - THIS IS AGGREGATED.  A MULT-STOP DELIVERY WILL BE REFLECTED AS 1 LOAD
/********************************************************************************************************************/
LOAD_OTD_SERVICE AS (SELECT LOAD_ID, TEAM_NAME, TEAM_GROUP, MAX(BASE_APPOINTMENT_DATETIME) AS "LAST_STOP_BASE_APPT_DATETIME", MAX(FINAL_APPOINTMENT_DATETIME) AS "LAST_STOP_FINAL_APPT_DATETIME",
  MAX(ARRIVED_AT_DATETIME) AS "LAST_STOP_ACTUAL_ARRIVAL",
  CASE WHEN MAX(CAPS_LATE) = ''Y'' THEN 0 ELSE 1 END AS "CAPS_ONTIME_CNT",
  MIN(CAPS_REASON) AS "CAPS_REASON_CD",
  CASE WHEN MAX(CSRS_LATE) = ''Y'' THEN 0 ELSE 1 END AS "CSRS_ONTIME_CNT",
  MIN(CSRS_REASON) AS "CSRS_REASON_CD",
  COUNT(LOAD_ID) AS STOP_CNT,
  SUM(CASE WHEN ARRIVED_AT_DATETIME IS NOT NULL AND CAPS_REASON <> ''MEFC'' THEN 1 ELSE 0 END) AS "STOP_RESPONSE_CNT",
  SUM(CASE WHEN ARRIVED_AT_DATETIME IS NOT NULL AND CAPS_LATE = ''N'' THEN 1 ELSE 0 END) AS "CAPS_ONTIME_STOP_CNT",
  SUM(CASE WHEN ARRIVED_AT_DATETIME IS NOT NULL AND CSRS_LATE = ''N'' THEN 1 ELSE 0 END) AS "CSRS_ONTIME_STOP_CNT"
FROM NAJDATRN.ABPP_OTC_CAPS_MASTER WHERE STOP_NUM > 1 GROUP BY LOAD_ID,TEAM_NAME,TEAM_GROUP),
/********************************************************************************************************************
/* GET PICK LOCATION AND ACTUAL PICK TIME FROM CAPS WHEN IT EXISTS 
/********************************************************************************************************************/
CAPS_PICK_STOPS AS (
SELECT LOAD_ID, LOCATION_NUM AS "PICK_LOCATION_ID", BASE_APPOINTMENT_DATETIME AS "PICK_APPOINTMENT_DATETIME", DEPARTED_DATETIME AS "CARR_DEPARTED_PICK_DATETIME", TEAM_NAME, TEAM_GROUP
FROM NAJDATRN.ABPP_OTC_CAPS_MASTER WHERE STOP_NUM =1
),
/********************************************************************************************************************
/* GET BASE AND FINAL APPOINTMENTS FROM THE FIRST DROP STOP
/********************************************************************************************************************/
CAPS_FIRST_DROP_STOPS AS (
SELECT LOAD_ID, BASE_APPOINTMENT_DATETIME AS "DROP_APPOINTMENT_DATETIME", ARRIVED_AT_DATETIME AS "CARR_ARRIVE_FRST_DROP_DATE"
FROM NAJDATRN.ABPP_OTC_CAPS_MASTER WHERE STOP_NUM =2
),
/********************************************************************************************************************
/* GET THE DISTANCE TO FIRST DROP STOP PLUS CURRENT APPOINTMENT 
/********************************************************************************************************************/
DIST_TO_FIRST_DROP AS (
SELECT SR.LD_LEG_ID, SR.FRMPREVSTOP_DIST, AR.APT_FRM_DTT AS "CURRENT_FRMAPT_DATETIME", AR.APT_TO_DTT AS "CURRENT_TOAPT_DATETIME", AD.CTY_NAME, AD.STA_CD
FROM NAJDAADM.STOP_R SR 
JOIN NAJDAADM.ADDRESS_R AD ON AD.ADDR_ID = SR.ADDR_ID
LEFT OUTER JOIN NAJDAADM.APPOINTMENT_R AR ON SR.APT_ID=AR.APT_ID 
WHERE SEQ_NUM = 2
)
/********************************************************************************************************************
/* METRICS QUERY
/********************************************************************************************************************/
SELECT 
LLR.LD_LEG_ID,
SO.SALES_ORG,
FT.FREIGHT_TYPE,
CASE    WHEN SO.SALES_ORG IN (''2810'',''2820'',''Z01'') THEN ''KCNA''
        WHEN SO.SALES_ORG IN (''2811'',''2821'',''Z02'',''Z04'',''Z06'',''Z07'') THEN ''KCP'' 
        WHEN SO.SALES_ORG = ''Z05'' THEN CAR.CORP1_ID
        WHEN SO.SALES_ORG IS NULL AND SUBSTR(LAR.CORP1_ID,1,2) = ''RF'' THEN ''KCP'' 
        WHEN SO.SALES_ORG IS NULL AND SUBSTR(LAR.CORP1_ID,1,2) <> ''RF'' THEN CAR.CORP1_ID
END AS "BUSINESS_UNIT",
STAT.STAT_SHRT_DESC AS "LOAD_STATUS",
LLR.CARR_CD,
LLR.SRVC_CD,
LLR.EQMT_TYP,
CASE
    WHEN SUBSTR(LLR.FRST_SHPG_LOC_CD,5,1) = ''-'' AND SUBSTR(LLR.LAST_SHPG_LOC_CD,5,1) = ''-'' THEN ''STO'' 
    WHEN SUBSTR(LLR.FRST_SHPG_LOC_CD,5,1) = ''-'' AND SUBSTR(LLR.LAST_SHPG_LOC_CD,1,1) = ''5'' THEN ''CUSTOMER''
    WHEN SUBSTR(LLR.FRST_SHPG_LOC_CD,5,1) = ''-'' AND LLR.LAST_SHPG_LOC_CD = ''99999999'' THEN ''CUSTOMER''
    WHEN SUBSTR(LLR.FRST_SHPG_LOC_CD,1,1) = ''V'' AND SUBSTR(LAR.CORP1_ID,1,2) = ''RM'' THEN ''MATERIALS''
    WHEN SUBSTR(LLR.FRST_SHPG_LOC_CD,1,1) = ''V'' AND SUBSTR(LAR.CORP1_ID,1,2) = ''RF'' THEN ''RECFIBER''
    ELSE ''UNKNOWN''
END AS "SHIP_TYPE",
CASE WHEN LAR.CORP2_ID IS NULL THEN LAR.NAME ELSE LAR.CORP2_ID END AS SHIP_FROM_NAME,
LLR.FRST_CTY_NAME || '', '' || LLR.FRST_STA_CD || '' to '' || CASE WHEN LLR.LAST_CTRY_CD = ''USA'' THEN SUBSTR(LLR.LAST_PSTL_CD,1,5) ELSE LLR.LAST_CTY_NAME || '', '' || LLR.LAST_STA_CD END AS "LANE_DESC",
LLR.FRST_SHPG_LOC_CD,
LLR.FRST_CTY_NAME,
LLR.FRST_STA_CD,
CASE 
  WHEN LLR.FRST_CTRY_CD = ''USA'' THEN SUBSTR(LLR.FRST_PSTL_CD,1,5) 
  WHEN LLR.FRST_CTRY_CD = ''CAN'' THEN SUBSTR(LLR.FRST_PSTL_CD,1,6)
  ELSE LLR.FRST_PSTL_CD
END AS FRST_ZIP_CD,
LLR.FRST_CTRY_CD,
LLR.LAST_SHPG_LOC_CD,
CASE
    WHEN CUSTOMER_GROUPINGS.CUSTOMER IS NOT NULL THEN CUSTOMER_GROUPINGS.CUSTOMER
    ELSE 
        CASE
            WHEN SUBSTR(LLR.LAST_SHPG_LOC_CD,5,1)=''-'' THEN ''K-C''
            WHEN SUBSTR(LLR.LAST_SHPG_LOC_CD,1,2)=''58'' THEN ''OTHER CUSTOMER''
            WHEN SUBSTR(LLR.LAST_SHPG_LOC_CD,5,1)=''99999999'' THEN ''OTHER CUSTOMER''
            WHEN SUBSTR(LLR.LAST_SHPG_LOC_CD,1,2)=''AK'' THEN ''HUB''
            WHEN SUBSTR(LLR.LAST_SHPG_LOC_CD,1,2)=''HI'' THEN ''HUB''
            WHEN SUBSTR(LLR.LAST_SHPG_LOC_CD,1,4)=''LCL-'' THEN ''HUB''
            ELSE ''UNKNOWN''
        END
END AS "SELL_TO_CUST",
LLR.LAST_CTY_NAME AS "FINAL_CITY_NAME",
LLR.LAST_STA_CD AS "FINAL_STA_CD",
LLR.LAST_CTRY_CD AS "FINAL_CTRY_CD",
CASE 
  WHEN LLR.LAST_CTRY_CD = ''USA'' THEN SUBSTR(LLR.LAST_PSTL_CD,1,5) 
  WHEN LLR.LAST_CTRY_CD = ''CAN'' THEN SUBSTR(LLR.LAST_PSTL_CD,1,6)
  ELSE LLR.LAST_PSTL_CD
END AS FINAL_ZIP_CD,
DTFD.FRMPREVSTOP_DIST AS "DISTANCE_TO_FRST_STOP",
CPS.TEAM_NAME,
CPS.TEAM_GROUP,
LLR.CHGD_AMT_DLR,
TRUNC(FT.TDR_DTT) AS "FRST_TENDER_DATE",
CPS.PICK_APPOINTMENT_DATETIME,
CPS.CARR_DEPARTED_PICK_DATETIME,
CASE WHEN LLR.SHPD_DTT IS NULL THEN TRUNC(CPS.PICK_APPOINTMENT_DATETIME) ELSE LLR.SHPD_DTT END AS SHIP_DATE ,
CASE 
  WHEN LLR.SHPD_DTT IS NULL THEN TO_CHAR(CPS.PICK_APPOINTMENT_DATETIME-1,''D'')  || ''-'' || TO_CHAR(CPS.PICK_APPOINTMENT_DATETIME,''DY'') 
  ELSE TO_CHAR(LLR.SHPD_DTT-1,''D'')  || ''-'' || TO_CHAR(LLR.SHPD_DTT,''DY'') 
END AS SHIP_DOW,
CASE 
  WHEN LLR.SHPD_DTT IS NULL THEN TRUNC(CPS.PICK_APPOINTMENT_DATETIME,''IW'')
  ELSE TRUNC(LLR.SHPD_DTT,''IW'')
END AS SHIP_WEEK,
CASE 
  WHEN LLR.SHPD_DTT IS NULL THEN TRUNC(CPS.PICK_APPOINTMENT_DATETIME,''MM'')
  ELSE TRUNC(LLR.SHPD_DTT,''MM'')
END AS SHIP_MONTH,
LOS.LAST_STOP_BASE_APPT_DATETIME,
LOS.LAST_STOP_FINAL_APPT_DATETIME,
TO_CHAR(LOS.LAST_STOP_FINAL_APPT_DATETIME-1,''D'')  || ''-'' || TO_CHAR(LOS.LAST_STOP_FINAL_APPT_DATETIME,''DY'') AS FINAL_APPT_DOW,
TRUNC(LOS.LAST_STOP_FINAL_APPT_DATETIME,''IW'') AS FINAL_APPT_WEEK,
TRUNC(LOS.LAST_STOP_FINAL_APPT_DATETIME,''MM'') AS FINAL_APPT_MONTH,
TRUNC(LOS.LAST_STOP_ACTUAL_ARRIVAL) AS "ACTUAL_DELIVERY_DATE",
TO_CHAR(LOS.LAST_STOP_ACTUAL_ARRIVAL-1,''D'')  || ''-'' || TO_CHAR(LOS.LAST_STOP_ACTUAL_ARRIVAL,''DY'') AS ACTUAL_DELIVERY_DOW,
TRUNC(LOS.LAST_STOP_ACTUAL_ARRIVAL,''IW'') AS ACTUAL_DELIVERY_WEEK,
TRUNC(LOS.LAST_STOP_ACTUAL_ARRIVAL,''MM'') AS ACTUAL_DELIVERY_MONTH,
LLR.MILE_DIST AS "TOTAL_MILES",
1 AS "LOAD_COUNT",
LOS.STOP_CNT AS "STOP_COUNT",
LOS.STOP_RESPONSE_CNT AS "STOP_RESPONSE_COUNT",
FT.FTA_CNT,
FT.TDR_LEAD_HRS,
CASE 
  WHEN LLR.EQMT_TYP = ''53IM'' THEN
    CASE 
      WHEN CPS.CARR_DEPARTED_PICK_DATETIME IS NULL AND SYSDATE > TRUNC(CPS.PICK_APPOINTMENT_DATETIME) + 1 THEN 0 
      WHEN CPS.CARR_DEPARTED_PICK_DATETIME IS NULL AND SYSDATE <= TRUNC(CPS.PICK_APPOINTMENT_DATETIME) + 1 THEN 1 
      WHEN CPS.CARR_DEPARTED_PICK_DATETIME IS NOT NULL AND CPS.CARR_DEPARTED_PICK_DATETIME > TRUNC(CPS.PICK_APPOINTMENT_DATETIME) + 1 THEN 0 
      ELSE 1 
    END
  ELSE
    CASE 
      WHEN CPS.CARR_DEPARTED_PICK_DATETIME IS NULL AND SYSDATE > CDS.DROP_APPOINTMENT_DATETIME - (((DTFD.FRMPREVSTOP_DIST / 46) + ((FLOOR((DTFD.FRMPREVSTOP_DIST / 46)/11)*11)+2))/24) THEN 0 
      WHEN CPS.CARR_DEPARTED_PICK_DATETIME IS NULL AND SYSDATE <= CDS.DROP_APPOINTMENT_DATETIME - (((DTFD.FRMPREVSTOP_DIST / 46) + ((FLOOR((DTFD.FRMPREVSTOP_DIST / 46)/11)*11)+2))/24) THEN 1 
      WHEN CPS.CARR_DEPARTED_PICK_DATETIME IS NOT NULL AND CPS.CARR_DEPARTED_PICK_DATETIME > CDS.DROP_APPOINTMENT_DATETIME - (((DTFD.FRMPREVSTOP_DIST / 46) + ((FLOOR((DTFD.FRMPREVSTOP_DIST / 46)/11)*11)+2))/24) THEN 0 
      ELSE 1 
    END
END AS "CAPS_OTP_CNT",
LOS.CAPS_ONTIME_CNT AS "CAPS_OTD_CNT",
LOS.CAPS_ONTIME_STOP_CNT AS "CAPS_OTD_STOP_CNT",
CASE WHEN RSD1.REASON_DESC IS NULL THEN LOS.CAPS_REASON_CD ELSE RSD1.REASON_DESC END AS "CAPS_REASON_DESC",
LOS.CSRS_ONTIME_CNT AS "CSRS_OTD_CNT",
LOS.CSRS_ONTIME_STOP_CNT AS "CSRS_OTD_STOP_CNT",
CASE WHEN RSD2.REASON_DESC IS NULL THEN LOS.CSRS_REASON_CD ELSE RSD2.REASON_DESC END AS "CSRS_REASON_DESC",
TRUNC(SYSDATE, ''MI'') AS "LAST_REFRESHED_TIME",
CASE WHEN MAX(CASE WHEN latr.origin_id IS NULL THEN 0 ELSE 1 END) = 0 THEN ''Not Award Lane'' ELSE ''Award Lane'' END AS AWARD_LANE_STATUS,
MAX(CASE WHEN latr.origin_id IS NULL THEN 0 ELSE 1 END) AS AWARD_LANE_CNT,
CASE WHEN MAX(CASE WHEN lasa.tariff_service IS NULL THEN 0 ELSE 1 END) = 0 THEN ''Not Award Carrier'' ELSE ''Award Carrier'' END AS AWARD_SERVICE_STATUS,
MAX(CASE WHEN lasa.tariff_service IS NULL THEN 0 ELSE 1 END) AS AWARD_SERVICE_CNT
FROM 
NAJDAADM.LOAD_LEG_R LLR
JOIN NAJDAADM.LOAD_AT_R LAR ON LLR.FRST_SHPG_LOC_CD = LAR.SHPG_LOC_CD 
LEFT OUTER JOIN NAJDAADM.CONSIGNEE_R CAR ON LLR.LAST_SHPG_LOC_CD = CAR.SHPG_LOC_CD 
JOIN NAJDAADM.STATUS_R STAT ON LLR.CUR_OPTLSTAT_ID = STAT.STAT_ID  
JOIN CAPS_PICK_STOPS CPS ON CPS.LOAD_ID=LLR.LD_LEG_ID
JOIN CAPS_FIRST_DROP_STOPS CDS ON CDS.LOAD_ID=LLR.LD_LEG_ID
JOIN LOAD_OTD_SERVICE LOS ON LOS.LOAD_ID = LLR.LD_LEG_ID
JOIN FIRST_TENDER FT ON FT.LD_LEG_ID = LLR.LD_LEG_ID
JOIN DIST_TO_FIRST_DROP DTFD ON DTFD.LD_LEG_ID = LLR.LD_LEG_ID 
JOIN SALES_ORG SO ON SO.LD_LEG_ID = LLR.LD_LEG_ID
JOIN FREIGHT_TYPE FT ON FT.LD_LEG_ID = LLR.LD_LEG_ID
LEFT OUTER JOIN CUSTOMER_GROUPINGS ON CUSTOMER_GROUPINGS.HIERARCHY = SUBSTR(LLR.LAST_SHPG_LOC_CD,1,8)
LEFT OUTER JOIN REASON_CODE_DESC RSD1 ON LOS.CAPS_REASON_CD = RSD1.REASON_CODE
LEFT OUTER JOIN REASON_CODE_DESC RSD2 ON LOS.CSRS_REASON_CD = RSD2.REASON_CODE
LEFT OUTER JOIN NAJDATRN.ABPP_LANESERVICEAWARDS   LASA   ON LASA.ORIGIN_ID = LLR.FRST_SHPG_LOC_CD
                                                AND LASA.DESTINATION_ID = LLR.LAST_SHPG_LOC_CD
                                                AND LASA.TARIFF_SERVICE = LLR.SRVC_CD
                                                AND LLR.STRD_DTT BETWEEN LASA.FROM_DATE AND LASA.TO_DATE
LEFT OUTER JOIN NAJDATRN.ABPP_LANEAWARDS_TL_R     LATR   ON LATR.ORIGIN_ID = LLR.FRST_SHPG_LOC_CD
                                                AND LATR.DESTINATION_ID = LLR.LAST_SHPG_LOC_CD
                                                AND LLR.STRD_DTT BETWEEN LATR.FROM_DATE AND LATR.TO_DATE
WHERE LLR.CUR_OPTLSTAT_ID BETWEEN 315 AND 350 AND
LLR.EQMT_TYP IN (''48FT'',''53FT'',''53IM'',''53RT'',''53TC'',''53HC'')


GROUP BY LLR.LD_LEG_ID, SO.SALES_ORG, FT.FREIGHT_TYPE, 
CASE    WHEN SO.SALES_ORG IN (''2810'',''2820'',''Z01'') THEN ''KCNA''
        WHEN SO.SALES_ORG IN (''2811'',''2821'',''Z02'',''Z04'',''Z06'',''Z07'') THEN ''KCP'' 
        WHEN SO.SALES_ORG = ''Z05'' THEN CAR.CORP1_ID
        WHEN SO.SALES_ORG IS NULL AND SUBSTR(LAR.CORP1_ID,1,2) = ''RF'' THEN ''KCP'' 
        WHEN SO.SALES_ORG IS NULL AND SUBSTR(LAR.CORP1_ID,1,2) <> ''RF'' THEN CAR.CORP1_ID
END,
STAT.STAT_SHRT_DESC, LLR.CARR_CD, LLR.SRVC_CD, LLR.EQMT_TYP, 
CASE
    WHEN SUBSTR(LLR.FRST_SHPG_LOC_CD,5,1) = ''-'' AND SUBSTR(LLR.LAST_SHPG_LOC_CD,5,1) = ''-'' THEN ''STO'' 
    WHEN SUBSTR(LLR.FRST_SHPG_LOC_CD,5,1) = ''-'' AND SUBSTR(LLR.LAST_SHPG_LOC_CD,1,1) = ''5'' THEN ''CUSTOMER''
    WHEN SUBSTR(LLR.FRST_SHPG_LOC_CD,5,1) = ''-'' AND LLR.LAST_SHPG_LOC_CD = ''99999999'' THEN ''CUSTOMER''
    WHEN SUBSTR(LLR.FRST_SHPG_LOC_CD,1,1) = ''V'' AND SUBSTR(LAR.CORP1_ID,1,2) = ''RM'' THEN ''MATERIALS''
    WHEN SUBSTR(LLR.FRST_SHPG_LOC_CD,1,1) = ''V'' AND SUBSTR(LAR.CORP1_ID,1,2) = ''RF'' THEN ''RECFIBER''
    ELSE ''UNKNOWN''
END,
CASE WHEN LAR.CORP2_ID IS NULL THEN LAR.NAME ELSE LAR.CORP2_ID END,
LLR.FRST_CTY_NAME || '', '' || LLR.FRST_STA_CD || '' to '' || CASE WHEN LLR.LAST_CTRY_CD = ''USA'' THEN SUBSTR(LLR.LAST_PSTL_CD,1,5) ELSE LLR.LAST_CTY_NAME || '', '' || LLR.LAST_STA_CD END, LLR.FRST_SHPG_LOC_CD, LLR.FRST_CTY_NAME, 
LLR.FRST_STA_CD, CASE WHEN LLR.FRST_CTRY_CD = ''USA'' THEN SUBSTR(LLR.FRST_PSTL_CD,1,5) WHEN LLR.FRST_CTRY_CD = ''CAN'' THEN SUBSTR(LLR.FRST_PSTL_CD,1,6) ELSE LLR.FRST_PSTL_CD END, LLR.FRST_CTRY_CD, LLR.LAST_SHPG_LOC_CD, CASE WHEN CUSTOMER_GROUPINGS.CUSTOMER IS NOT NULL THEN CUSTOMER_GROUPINGS.CUSTOMER ELSE CASE WHEN SUBSTR(LLR.LAST_SHPG_LOC_CD,5,1)=''-'' THEN ''K-C'' WHEN SUBSTR(LLR.LAST_SHPG_LOC_CD,1,2)=''58'' THEN ''OTHER CUSTOMER'' WHEN SUBSTR(LLR.LAST_SHPG_LOC_CD,5,1)=''99999999'' THEN ''OTHER CUSTOMER'' WHEN SUBSTR(LLR.LAST_SHPG_LOC_CD,1,2)=''AK'' THEN ''HUB'' WHEN SUBSTR(LLR.LAST_SHPG_LOC_CD,1,2)=''HI'' THEN ''HUB'' WHEN SUBSTR(LLR.LAST_SHPG_LOC_CD,1,4)=''LCL-'' THEN ''HUB'' ELSE ''UNKNOWN'' END END, 
LLR.LAST_CTY_NAME, LLR.LAST_STA_CD, LLR.LAST_CTRY_CD, CASE WHEN LLR.LAST_CTRY_CD = ''USA'' THEN SUBSTR(LLR.LAST_PSTL_CD,1,5) WHEN LLR.LAST_CTRY_CD = ''CAN'' THEN SUBSTR(LLR.LAST_PSTL_CD,1,6) ELSE LLR.LAST_PSTL_CD END, DTFD.FRMPREVSTOP_DIST, 
CPS.TEAM_NAME, CPS.TEAM_GROUP, LLR.CHGD_AMT_DLR, TRUNC(FT.TDR_DTT), CPS.PICK_APPOINTMENT_DATETIME, 
CPS.CARR_DEPARTED_PICK_DATETIME, CASE WHEN LLR.SHPD_DTT IS NULL THEN TRUNC(CPS.PICK_APPOINTMENT_DATETIME) ELSE LLR.SHPD_DTT END, CASE WHEN LLR.SHPD_DTT IS NULL THEN TO_CHAR(CPS.PICK_APPOINTMENT_DATETIME-1,''D'') || ''-'' || TO_CHAR(CPS.PICK_APPOINTMENT_DATETIME,''DY'') ELSE TO_CHAR(LLR.SHPD_DTT-1,''D'') || ''-'' || TO_CHAR(LLR.SHPD_DTT,''DY'') END, CASE WHEN LLR.SHPD_DTT IS NULL THEN TRUNC(CPS.PICK_APPOINTMENT_DATETIME,''IW'') ELSE TRUNC(LLR.SHPD_DTT,''IW'') END, CASE WHEN LLR.SHPD_DTT IS NULL THEN TRUNC(CPS.PICK_APPOINTMENT_DATETIME,''MM'') ELSE TRUNC(LLR.SHPD_DTT,''MM'') END, 
LOS.LAST_STOP_BASE_APPT_DATETIME, LOS.LAST_STOP_FINAL_APPT_DATETIME, TO_CHAR(LOS.LAST_STOP_FINAL_APPT_DATETIME-1,''D'') || ''-'' || TO_CHAR(LOS.LAST_STOP_FINAL_APPT_DATETIME,''DY''), TRUNC(LOS.LAST_STOP_FINAL_APPT_DATETIME,''IW''), TRUNC(LOS.LAST_STOP_FINAL_APPT_DATETIME,''MM''), 
TRUNC(LOS.LAST_STOP_ACTUAL_ARRIVAL), TO_CHAR(LOS.LAST_STOP_ACTUAL_ARRIVAL-1,''D'') || ''-'' || TO_CHAR(LOS.LAST_STOP_ACTUAL_ARRIVAL,''DY''), TRUNC(LOS.LAST_STOP_ACTUAL_ARRIVAL,''IW''), TRUNC(LOS.LAST_STOP_ACTUAL_ARRIVAL,''MM''), LLR.MILE_DIST, 
1, LOS.STOP_CNT, LOS.STOP_RESPONSE_CNT, FT.FTA_CNT, FT.TDR_LEAD_HRS, 
CASE WHEN LLR.EQMT_TYP = ''53IM'' THEN CASE WHEN CPS.CARR_DEPARTED_PICK_DATETIME IS NULL AND SYSDATE > TRUNC(CPS.PICK_APPOINTMENT_DATETIME) + 1 THEN 0 WHEN CPS.CARR_DEPARTED_PICK_DATETIME IS NULL AND SYSDATE <= TRUNC(CPS.PICK_APPOINTMENT_DATETIME) + 1 THEN 1 WHEN CPS.CARR_DEPARTED_PICK_DATETIME IS NOT NULL AND CPS.CARR_DEPARTED_PICK_DATETIME > TRUNC(CPS.PICK_APPOINTMENT_DATETIME) + 1 THEN 0 ELSE 1 END ELSE CASE WHEN CPS.CARR_DEPARTED_PICK_DATETIME IS NULL AND SYSDATE > CDS.DROP_APPOINTMENT_DATETIME - (((DTFD.FRMPREVSTOP_DIST / 46) + ((FLOOR((DTFD.FRMPREVSTOP_DIST / 46)/11)*11)+2))/24) THEN 0 WHEN CPS.CARR_DEPARTED_PICK_DATETIME IS NULL AND SYSDATE <= CDS.DROP_APPOINTMENT_DATETIME - (((DTFD.FRMPREVSTOP_DIST / 46) + ((FLOOR((DTFD.FRMPREVSTOP_DIST / 46)/11)*11)+2))/24) THEN 1 WHEN CPS.CARR_DEPARTED_PICK_DATETIME IS NOT NULL AND CPS.CARR_DEPARTED_PICK_DATETIME > CDS.DROP_APPOINTMENT_DATETIME - (((DTFD.FRMPREVSTOP_DIST / 46) + ((FLOOR((DTFD.FRMPREVSTOP_DIST / 46)/11)*11)+2))/24) THEN 0 ELSE 1 END END, LOS.CAPS_ONTIME_CNT, LOS.CAPS_ONTIME_STOP_CNT, CASE WHEN RSD1.REASON_DESC IS NULL THEN LOS.CAPS_REASON_CD ELSE RSD1.REASON_DESC END, LOS.CSRS_ONTIME_CNT, 
LOS.CSRS_ONTIME_STOP_CNT, CASE WHEN RSD2.REASON_DESC IS NULL THEN LOS.CSRS_REASON_CD ELSE RSD2.REASON_DESC END, TRUNC(SYSDATE, ''MI'')
'

/*
Create Temp table
*/
CREATE TABLE ##tblOperationalMetricsTemp 
  ( 
     LD_LEG_ID                     NVARCHAR(20), 
     SALES_ORG                     NVARCHAR(10), 
     FREIGHT_TYPE                  NVARCHAR(5), 
     BUSINESS_UNIT                 NVARCHAR(10), 
     LOAD_STATUS                   NVARCHAR(20), 
     CARR_CD                       NVARCHAR(5), 
     SRVC_CD                       NVARCHAR(5), 
     EQMT_TYP                      NVARCHAR(5), 
     SHIP_TYPE                     NVARCHAR(10), 
     SHIP_FROM_NAME                NVARCHAR(75), 
     LANE_DESC                     NVARCHAR(75), 
     FRST_SHPG_LOC_CD              NVARCHAR(20), 
     FRST_CTY_NAME                 NVARCHAR(50), 
     FRST_STA_CD                   NVARCHAR(2), 
     FRST_ZIP_CD                   NVARCHAR(10), 
     FRST_CTRY_CD                  NVARCHAR(3), 
     LAST_SHPG_LOC_CD              NVARCHAR(20), 
     SELL_TO_CUST                  NVARCHAR(40), 
     FINAL_CITY_NAME               NVARCHAR(50), 
     FINAL_STA_CD                  NVARCHAR(2), 
     FINAL_CTRY_CD                 NVARCHAR(3), 
     FINAL_ZIP_CD                  NVARCHAR(10), 
     DISTANCE_TO_FRST_STOP         NUMERIC(18, 2), 
     TEAM_NAME                     NVARCHAR(20), 
     TEAM_GROUP                    NVARCHAR(5), 
     CHGD_AMT_DLR                  NUMERIC(18, 2), 
     FRST_TENDER_DATE              DATETIME, 
     PICK_APPOINTMENT_DATETIME     DATETIME, 
     CARR_DEPARTED_PICK_DATETIME   DATETIME, 
     SHIP_DATE                     DATETIME, 
     SHIP_DOW                      NVARCHAR(5), 
     SHIP_WEEK                     DATETIME, 
     SHIP_MONTH                    DATETIME, 
     LAST_STOP_BASE_APPT_DATETIME  DATETIME, 
     LAST_STOP_FINAL_APPT_DATETIME DATETIME, 
     FINAL_APPT_DOW                NVARCHAR(5), 
     FINAL_APPT_WEEK               DATETIME, 
     FINAL_APPT_MONTH              DATETIME, 
     ACTUAL_DELIVERY_DATE          DATETIME, 
     ACTUAL_DELIVERY_DOW           NVARCHAR(10), 
     ACTUAL_DELIVERY_WEEK          DATETIME, 
     ACTUAL_DELIVERY_MONTH         DATETIME, 
     TOTAL_MILES                   NUMERIC(18, 2), 
     LOAD_COUNT                    INT, 
     STOP_COUNT                    INT, 
     STOP_RESPONSE_COUNT           INT, 
     FTA_CNT                       INT, 
     TDR_LEAD_HRS                  DECIMAL(18, 2), 
     CAPS_OTP_CNT                  INT, 
     CAPS_OTD_CNT                  INT, 
     CAPS_OTD_STOP_CNT             INT, 
     CAPS_REASON_DESC              NVARCHAR(50), 
     CSRS_OTD_CNT                  INT, 
     CSRS_OTD_STOP_CNT             INT, 
     CSRS_REASON_DESC              NVARCHAR(50), 
     LAST_REFRESHED_TIME           DATETIME, 
     AWARD_LANE_STATUS             NVARCHAR(20), 
     AWARD_LANE_CNT                INT, 
     AWARD_SERVICE_STATUS          NVARCHAR(20), 
     AWARD_SERVICE_CNT             INT 
  ) 

  /*
  Append records from giant Oracle query into MSSQL temp table
  */
  INSERT INTO ##tblOperationalMetricsTemp
  EXEC (@myQuery) AT NAJDAPRD

  /*
  Append new values from ##tblOperationalMetricsTemp to USCTTDEV.DBO.TBLOPERATIONALMETRICS, where the LD_LEG_ID value does not exist
  */
  INSERT INTO USCTTDEV.DBO.TBLOPERATIONALMETRICS 
            (LD_LEG_ID, 
             SALES_ORG, 
             FREIGHT_TYPE, 
             BUSINESS_UNIT, 
             LOAD_STATUS, 
             CARR_CD, 
             SRVC_CD, 
             EQMT_TYP, 
             SHIP_TYPE, 
             SHIP_FROM_NAME, 
             LANE_DESC, 
             FRST_SHPG_LOC_CD, 
             FRST_CTY_NAME, 
             FRST_STA_CD, 
             FRST_ZIP_CD, 
             FRST_CTRY_CD, 
             LAST_SHPG_LOC_CD, 
             SELL_TO_CUST, 
             FINAL_CITY_NAME, 
             FINAL_STA_CD, 
             FINAL_CTRY_CD, 
             FINAL_ZIP_CD, 
             DISTANCE_TO_FRST_STOP, 
             TEAM_NAME, 
             TEAM_GROUP, 
             CHGD_AMT_DLR, 
             FRST_TENDER_DATE, 
             PICK_APPOINTMENT_DATETIME, 
             CARR_DEPARTED_PICK_DATETIME, 
             SHIP_DATE, 
             SHIP_DOW, 
             SHIP_WEEK, 
             SHIP_MONTH, 
             LAST_STOP_BASE_APPT_DATETIME, 
             LAST_STOP_FINAL_APPT_DATETIME, 
             FINAL_APPT_DOW, 
             FINAL_APPT_WEEK, 
             FINAL_APPT_MONTH, 
             ACTUAL_DELIVERY_DATE, 
             ACTUAL_DELIVERY_DOW, 
             ACTUAL_DELIVERY_WEEK, 
             ACTUAL_DELIVERY_MONTH, 
             TOTAL_MILES, 
             LOAD_COUNT, 
             STOP_COUNT, 
             STOP_RESPONSE_COUNT, 
             FTA_CNT, 
             TDR_LEAD_HRS, 
             CAPS_OTP_CNT, 
             CAPS_OTD_CNT, 
             CAPS_OTD_STOP_CNT, 
             CAPS_REASON_DESC, 
             CSRS_OTD_CNT, 
             CSRS_OTD_STOP_CNT, 
             CSRS_REASON_DESC, 
             LAST_REFRESHED_TIME, 
             AWARD_LANE_STATUS, 
             AWARD_LANE_CNT, 
             AWARD_SERVICE_STATUS, 
             AWARD_SERVICE_CNT) 
SELECT OMT.LD_LEG_ID, 
       OMT.SALES_ORG, 
       OMT.FREIGHT_TYPE, 
       OMT.BUSINESS_UNIT, 
       OMT.LOAD_STATUS, 
       OMT.CARR_CD, 
       OMT.SRVC_CD, 
       OMT.EQMT_TYP, 
       OMT.SHIP_TYPE, 
       OMT.SHIP_FROM_NAME, 
       OMT.LANE_DESC, 
       OMT.FRST_SHPG_LOC_CD, 
       OMT.FRST_CTY_NAME, 
       OMT.FRST_STA_CD, 
       OMT.FRST_ZIP_CD, 
       OMT.FRST_CTRY_CD, 
       OMT.LAST_SHPG_LOC_CD, 
       OMT.SELL_TO_CUST, 
       OMT.FINAL_CITY_NAME, 
       OMT.FINAL_STA_CD, 
       OMT.FINAL_CTRY_CD, 
       OMT.FINAL_ZIP_CD, 
       OMT.DISTANCE_TO_FRST_STOP, 
       OMT.TEAM_NAME, 
       OMT.TEAM_GROUP, 
       OMT.CHGD_AMT_DLR, 
       OMT.FRST_TENDER_DATE, 
       OMT.PICK_APPOINTMENT_DATETIME, 
       OMT.CARR_DEPARTED_PICK_DATETIME, 
       OMT.SHIP_DATE, 
       OMT.SHIP_DOW, 
       OMT.SHIP_WEEK, 
       OMT.SHIP_MONTH, 
       OMT.LAST_STOP_BASE_APPT_DATETIME, 
       OMT.LAST_STOP_FINAL_APPT_DATETIME, 
       OMT.FINAL_APPT_DOW, 
       OMT.FINAL_APPT_WEEK, 
       OMT.FINAL_APPT_MONTH, 
       OMT.ACTUAL_DELIVERY_DATE, 
       OMT.ACTUAL_DELIVERY_DOW, 
       OMT.ACTUAL_DELIVERY_WEEK, 
       OMT.ACTUAL_DELIVERY_MONTH, 
       OMT.TOTAL_MILES, 
       OMT.LOAD_COUNT, 
       OMT.STOP_COUNT, 
       OMT.STOP_RESPONSE_COUNT, 
       OMT.FTA_CNT, 
       OMT.TDR_LEAD_HRS, 
       OMT.CAPS_OTP_CNT, 
       OMT.CAPS_OTD_CNT, 
       OMT.CAPS_OTD_STOP_CNT, 
       OMT.CAPS_REASON_DESC, 
       OMT.CSRS_OTD_CNT, 
       OMT.CSRS_OTD_STOP_CNT, 
       OMT.CSRS_REASON_DESC, 
       OMT.LAST_REFRESHED_TIME, 
       OMT.AWARD_LANE_STATUS, 
       OMT.AWARD_LANE_CNT, 
       OMT.AWARD_SERVICE_STATUS, 
       OMT.AWARD_SERVICE_CNT 
FROM   ##TBLOPERATIONALMETRICSTEMP AS OMT 
       LEFT JOIN USCTTDEV.DBO.TBLOPERATIONALMETRICS OM 
              ON OM.LD_LEG_ID = OMT.LD_LEG_ID 
WHERE  OM.LD_LEG_ID IS NULL 


/*
Declare and set variable for current date/time to use on AddedOn/LastUpdated
*/
DECLARE @currentDateTime as datetime
SET @currentDateTime = GETDATE()

/*
Update ALL fields on MSSQL Server table to match what's currently in Temp table
*/
UPDATE OM
SET 
OM.AddedOn = CASE WHEN OM.AddedOn is null then @currentDateTime else OM.AddedOn END,
OM.LastUpdated = @currentDateTime,
OM.LD_LEG_ID = OMT.LD_LEG_ID,
OM.SALES_ORG = OMT.SALES_ORG,
OM.FREIGHT_TYPE = OMT.FREIGHT_TYPE,
OM.BUSINESS_UNIT = OMT.BUSINESS_UNIT,
OM.LOAD_STATUS = OMT.LOAD_STATUS,
OM.CARR_CD = OMT.CARR_CD,
OM.SRVC_CD = OMT.SRVC_CD,
OM.EQMT_TYP = OMT.EQMT_TYP,
OM.SHIP_TYPE = OMT.SHIP_TYPE,
OM.SHIP_FROM_NAME = OMT.SHIP_FROM_NAME,
OM.LANE_DESC = OMT.LANE_DESC,
OM.FRST_SHPG_LOC_CD = OMT.FRST_SHPG_LOC_CD,
OM.FRST_CTY_NAME = OMT.FRST_CTY_NAME,
OM.FRST_STA_CD = OMT.FRST_STA_CD,
OM.FRST_ZIP_CD = OMT.FRST_ZIP_CD,
OM.FRST_CTRY_CD = OMT.FRST_CTRY_CD,
OM.LAST_SHPG_LOC_CD = OMT.LAST_SHPG_LOC_CD,
OM.SELL_TO_CUST = OMT.SELL_TO_CUST,
OM.FINAL_CITY_NAME = OMT.FINAL_CITY_NAME,
OM.FINAL_STA_CD = OMT.FINAL_STA_CD,
OM.FINAL_CTRY_CD = OMT.FINAL_CTRY_CD,
OM.FINAL_ZIP_CD = OMT.FINAL_ZIP_CD,
OM.DISTANCE_TO_FRST_STOP = OMT.DISTANCE_TO_FRST_STOP,
OM.TEAM_NAME = OMT.TEAM_NAME,
OM.TEAM_GROUP = OMT.TEAM_GROUP,
OM.CHGD_AMT_DLR = OMT.CHGD_AMT_DLR,
OM.FRST_TENDER_DATE = OMT.FRST_TENDER_DATE,
OM.PICK_APPOINTMENT_DATETIME = OMT.PICK_APPOINTMENT_DATETIME,
OM.CARR_DEPARTED_PICK_DATETIME = OMT.CARR_DEPARTED_PICK_DATETIME,
OM.SHIP_DATE = OMT.SHIP_DATE,
OM.SHIP_DOW = OMT.SHIP_DOW,
OM.SHIP_WEEK = OMT.SHIP_WEEK,
OM.SHIP_MONTH = OMT.SHIP_MONTH,
OM.LAST_STOP_BASE_APPT_DATETIME = OMT.LAST_STOP_BASE_APPT_DATETIME,
OM.LAST_STOP_FINAL_APPT_DATETIME = OMT.LAST_STOP_FINAL_APPT_DATETIME,
OM.FINAL_APPT_DOW = OMT.FINAL_APPT_DOW,
OM.FINAL_APPT_WEEK = OMT.FINAL_APPT_WEEK,
OM.FINAL_APPT_MONTH = OMT.FINAL_APPT_MONTH,
OM.ACTUAL_DELIVERY_DATE = OMT.ACTUAL_DELIVERY_DATE,
OM.ACTUAL_DELIVERY_DOW = OMT.ACTUAL_DELIVERY_DOW,
OM.ACTUAL_DELIVERY_WEEK = OMT.ACTUAL_DELIVERY_WEEK,
OM.ACTUAL_DELIVERY_MONTH = OMT.ACTUAL_DELIVERY_MONTH,
OM.TOTAL_MILES = OMT.TOTAL_MILES,
OM.LOAD_COUNT = OMT.LOAD_COUNT,
OM.STOP_COUNT = OMT.STOP_COUNT,
OM.STOP_RESPONSE_COUNT = OMT.STOP_RESPONSE_COUNT,
OM.FTA_CNT = OMT.FTA_CNT,
OM.TDR_LEAD_HRS = OMT.TDR_LEAD_HRS,
OM.CAPS_OTP_CNT = OMT.CAPS_OTP_CNT,
OM.CAPS_OTD_CNT = OMT.CAPS_OTD_CNT,
OM.CAPS_OTD_STOP_CNT = OMT.CAPS_OTD_STOP_CNT,
OM.CAPS_REASON_DESC = OMT.CAPS_REASON_DESC,
OM.CSRS_OTD_CNT = OMT.CSRS_OTD_CNT,
OM.CSRS_OTD_STOP_CNT = OMT.CSRS_OTD_STOP_CNT,
OM.CSRS_REASON_DESC = OMT.CSRS_REASON_DESC,
OM.LAST_REFRESHED_TIME = OMT.LAST_REFRESHED_TIME,
OM.AWARD_LANE_STATUS = OMT.AWARD_LANE_STATUS,
OM.AWARD_LANE_CNT = OMT.AWARD_LANE_CNT,
OM.AWARD_SERVICE_STATUS = OMT.AWARD_SERVICE_STATUS,
OM.AWARD_SERVICE_CNT = OMT.AWARD_SERVICE_CNT

FROM USCTTDEV.DBO.TBLOPERATIONALMETRICS AS OM
INNER JOIN   ##TBLOPERATIONALMETRICSTEMP AS OMT 
              ON OM.LD_LEG_ID = OMT.LD_LEG_ID 

/*
Redundant, but I do it anyway! : D 
Delete Temp table, if exists
*/
DROP TABLE IF EXISTS
##tblOperationalMetricsTemp