SELECT DISTINCT 

ald.Lane,
Rank() OVER (PARTITION BY ald.Lane, ald.LAST_SHPG_LOC_CD, ald.BU ORDER BY CAST(ald.WeekStartDate AS Date) ASC) AS Ordinal,
ald.LAST_SHPG_LOC_CD,
ald.LAST_SHPG_LOC_NAME,
ald.CustomerHierarchy,
ald.BU,
ald.WeekStartDate,
SUM(ald.TotalWeight) AS TotalWeight,
SUM(ald.TotalVolume) AS TotalVolume,
SUM(ald.TotalCost) AS TotalCost,
MIN(ald.TotalCost) AS MinCost,
COUNT(DISTINCT ald.LD_LEG_ID) AS LoadCount,
SUM(CASE WHEN ald.TotalVolume < 2000 THEN 1 ELSE 0 END) AS LowCubeLoadCount,
CASE WHEN COUNT(DISTINCT ald.LD_LEG_ID) > 1 AND SUM(CASE WHEN ald.TotalVolume < 2000 THEN 1 ELSE 0 END) >= 1 THEN CAST(CEILING(SUM(ald.TotalVolume/3200)) AS INT) ELSE COUNT(DISTINCT ald.LD_LEG_ID)  END AS ShouldHaveBeenTrucks,
COUNT(DISTINCT ald.LD_LEG_ID) - CASE WHEN COUNT(DISTINCT ald.LD_LEG_ID) > 1 AND SUM(CASE WHEN ald.TotalVolume < 2000 THEN 1 ELSE 0 END) >= 1 THEN CAST(CEILING(SUM(ald.TotalVolume/3200)) AS INT) ELSE COUNT(DISTINCT ald.LD_LEG_ID)  END AS AvoidableTrucks,
/*CAST(ROUND(CASE WHEN COUNT(DISTINCT ald.LD_LEG_ID) > 1 AND SUM(CASE WHEN ald.TOT_VOL < 2000 THEN 1 ELSE 0 END) >= 1 THEN CAST(CEILING(SUM(ald.TotalVolume/3200)) AS INT) ELSE COUNT(DISTINCT ald.LD_LEG_ID) END * MIN(ald.TotalCost) ,2) AS NUMERIC(10,2)) AS ShouldHaveBeenCost,*/
CASE WHEN COUNT(DISTINCT ald.LD_LEG_ID) - CASE WHEN COUNT(DISTINCT ald.LD_LEG_ID) > 1 AND SUM(CASE WHEN ald.TotalVolume < 2000 THEN 1 ELSE 0 END) >= 1 THEN CAST(CEILING(SUM(ald.TotalVolume/3200)) AS INT) ELSE COUNT(DISTINCT ald.LD_LEG_ID)  END > 0 THEN 
CAST(ROUND(CASE WHEN COUNT(DISTINCT ald.LD_LEG_ID) > 1 AND SUM(CASE WHEN ald.TotalVolume < 2000 THEN 1 ELSE 0 END) >= 1 THEN CAST(CEILING(SUM(ald.TotalVolume/3200)) AS INT) ELSE COUNT(DISTINCT ald.LD_LEG_ID) END * MIN(ald.TotalCost) ,2) AS NUMERIC(10,2))
ELSE SUM(ald.TotalCost) END AS ShouldHaveBeenCost,
SUM(ald.TotalCost) - CASE WHEN COUNT(DISTINCT ald.LD_LEG_ID) - CASE WHEN COUNT(DISTINCT ald.LD_LEG_ID) > 1 AND SUM(CASE WHEN ald.TotalVolume < 2000 THEN 1 ELSE 0 END) >= 1 THEN CAST(CEILING(SUM(ald.TotalVolume/3200)) AS INT) ELSE COUNT(DISTINCT ald.LD_LEG_ID)  END > 0 THEN 
CAST(ROUND(CASE WHEN COUNT(DISTINCT ald.LD_LEG_ID) > 1 AND SUM(CASE WHEN ald.TotalVolume < 2000 THEN 1 ELSE 0 END) >= 1 THEN CAST(CEILING(SUM(ald.TotalVolume/3200)) AS INT) ELSE COUNT(DISTINCT ald.LD_LEG_ID) END * MIN(ald.TotalCost) ,2) AS NUMERIC(10,2))
ELSE SUM(ald.TotalCost) END AS AvoidableCost


FROM
(
SELECT DISTINCT 
ald.Lane,
Rank() OVER (PARTITION BY ald.Lane, ald.LAST_SHPG_LOC_CD ORDER BY CAST(ald.SHPD_DTT AS Date) ASC, ald.LD_LEG_ID ASC ) AS Ordinal,
ald.LAST_SHPG_LOC_CD,
ald.LAST_SHPG_LOC_NAME,
ald.LD_LEG_ID,
ald.CustomerHierarchy,
ald.BU,
ald.BUSegment,

DATEADD(DD, 2 - DATEPART(DW, DATEADD(DD, -1, CAST(ald.SHPD_DTT AS Date))), DATEADD(DD, -1, CAST(ald.SHPD_DTT AS Date))) AS WeekStartDate,
SUM(ald.TotalWeight) AS TotalWeight,
SUM(ald.TotalVolume) AS TotalVolume,
SUM(ald.TotalCost) AS TotalCost,
MIN(ald.TotalCost) AS MinCost,
COUNT(DISTINCT ald.LD_LEG_ID) AS LoadCount,
SUM(CASE WHEN ald.TOT_VOL < 2000 THEN 1 ELSE 0 END) AS LowCubeLoadCount,
CASE WHEN COUNT(DISTINCT ald.LD_LEG_ID) > 1 AND SUM(CASE WHEN ald.TOT_VOL < 2000 THEN 1 ELSE 0 END) >= 1 THEN CAST(CEILING(SUM(ald.TotalVolume/3200)) AS INT) ELSE COUNT(DISTINCT ald.LD_LEG_ID)  END AS ShouldHaveBeenTrucks,
COUNT(DISTINCT ald.LD_LEG_ID) - CASE WHEN COUNT(DISTINCT ald.LD_LEG_ID) > 1 AND SUM(CASE WHEN ald.TOT_VOL < 2000 THEN 1 ELSE 0 END) >= 1 THEN CAST(CEILING(SUM(ald.TotalVolume/3200)) AS INT) ELSE COUNT(DISTINCT ald.LD_LEG_ID)  END AS AvoidableTrucks,
/*CAST(ROUND(CASE WHEN COUNT(DISTINCT ald.LD_LEG_ID) > 1 AND SUM(CASE WHEN ald.TOT_VOL < 2000 THEN 1 ELSE 0 END) >= 1 THEN CAST(CEILING(SUM(ald.TotalVolume/3200)) AS INT) ELSE COUNT(DISTINCT ald.LD_LEG_ID) END * MIN(ald.TotalCost) ,2) AS NUMERIC(10,2)) AS ShouldHaveBeenCost,*/
CASE WHEN COUNT(DISTINCT ald.LD_LEG_ID) - CASE WHEN COUNT(DISTINCT ald.LD_LEG_ID) > 1 AND SUM(CASE WHEN ald.TOT_VOL < 2000 THEN 1 ELSE 0 END) >= 1 THEN CAST(CEILING(SUM(ald.TotalVolume/3200)) AS INT) ELSE COUNT(DISTINCT ald.LD_LEG_ID)  END > 0 THEN 
CAST(ROUND(CASE WHEN COUNT(DISTINCT ald.LD_LEG_ID) > 1 AND SUM(CASE WHEN ald.TOT_VOL < 2000 THEN 1 ELSE 0 END) >= 1 THEN CAST(CEILING(SUM(ald.TotalVolume/3200)) AS INT) ELSE COUNT(DISTINCT ald.LD_LEG_ID) END * MIN(ald.TotalCost) ,2) AS NUMERIC(10,2))
ELSE SUM(ald.TotalCost) END AS ShouldHaveBeenCost,
SUM(ald.TotalCost) - CASE WHEN COUNT(DISTINCT ald.LD_LEG_ID) - CASE WHEN COUNT(DISTINCT ald.LD_LEG_ID) > 1 AND SUM(CASE WHEN ald.TOT_VOL < 2000 THEN 1 ELSE 0 END) >= 1 THEN CAST(CEILING(SUM(ald.TotalVolume/3200)) AS INT) ELSE COUNT(DISTINCT ald.LD_LEG_ID)  END > 0 THEN 
CAST(ROUND(CASE WHEN COUNT(DISTINCT ald.LD_LEG_ID) > 1 AND SUM(CASE WHEN ald.TOT_VOL < 2000 THEN 1 ELSE 0 END) >= 1 THEN CAST(CEILING(SUM(ald.TotalVolume/3200)) AS INT) ELSE COUNT(DISTINCT ald.LD_LEG_ID) END * MIN(ald.TotalCost) ,2) AS NUMERIC(10,2))
ELSE SUM(ald.TotalCost) END AS AvoidableCost

FROM USCTTDEV.dbo.tblActualLoadDetail ald
WHERE ald.EQMT_TYP <> 'LTL'
/*AND Lane = 'ARCONWAY-5GA30253'*/
/*AND ald.TotalVolume < 2000*/
AND ald.SHPD_DTT BETWEEN '1/4/2021' AND DATEADD(wk,DATEDIFF(wk,7,GETDATE()),6)
AND ald.BUSegment NOT IN ('Wadding','NFG','NONWOVENS')
AND YEAR(CAST(ald.SHPD_DTT AS DATE)) >= YEAR(GETDATE()) - 1

GROUP BY ald.Lane,

ald.LAST_SHPG_LOC_CD,
ald.LAST_SHPG_LOC_NAME,
ald.LD_LEG_ID,
ald.CustomerHierarchy,
ald.BU,
ald.BUSegment,
CAST(ald.SHPD_DTT AS Date)

/*HAVING COUNT(DISTINCT ald.LD_LEG_ID) > 2*/
)ald

GROUP BY ald.Lane,

ald.LAST_SHPG_LOC_CD,
ald.LAST_SHPG_LOC_NAME,
ald.CustomerHierarchy,
ald.BU,
ald.WeekStartDate

ORDER BY ald.Lane ASC, ald.LAST_SHPG_LOC_CD ASC, ald.BU ASC, Ordinal ASC