SELECT DISTINCT bar.LaneID,
bar.Lane,
CAST(ROUND(Percentile_Cont(0) WITHIN GROUP(ORDER BY bar.AllInCost ASC) OVER(PARTITION BY bar.LaneID),2) AS NUMERIC(10,2)) AS Min,
CAST(ROUND(Percentile_Cont(1) WITHIN GROUP(ORDER BY bar.AllInCost ASC) OVER(PARTITION BY bar.LaneID),2) AS NUMERIC(10,2)) AS Max,
CAST(ROUND(Percentile_Cont(0.25) WITHIN GROUP(ORDER BY bar.AllInCost ASC) OVER(PARTITION BY bar.LaneID),2) AS NUMERIC(10,2)) AS Q1,
CAST(ROUND(Percentile_Cont(0.50) WITHIN GROUP(ORDER BY bar.AllInCost ASC) OVER(PARTITION BY bar.LaneID),2) AS NUMERIC(10,2)) AS Median,
CAST(ROUND(Percentile_Cont(0.75) WITHIN GROUP(ORDER BY bar.AllInCost ASC) OVER(PARTITION BY bar.LaneID),2) AS NUMERIC(10,2)) AS Q3,
CAST(ROUND(Percentile_Cont(0.75) WITHIN GROUP(ORDER BY bar.AllInCost ASC) OVER(PARTITION BY bar.LaneID),2) AS NUMERIC(10,2)) - 
CAST(ROUND(Percentile_Cont(0.25) WITHIN GROUP(ORDER BY bar.AllInCost ASC) OVER(PARTITION BY bar.LaneID),2) AS NUMERIC(10,2)) AS IQR,
CAST(ROUND(1.5 * (CAST(ROUND(Percentile_Cont(0.75) WITHIN GROUP(ORDER BY bar.AllInCost ASC) OVER(PARTITION BY bar.LaneID),2) AS NUMERIC(10,2)) - 
CAST(ROUND(Percentile_Cont(0.25) WITHIN GROUP(ORDER BY bar.AllInCost ASC) OVER(PARTITION BY bar.LaneID),2) AS NUMERIC(10,2))) ,2) AS NUMERIC(10,2)) AS ControlLimitCalc,
CAST(ROUND(Percentile_Cont(0.25) WITHIN GROUP(ORDER BY bar.AllInCost ASC) OVER(PARTITION BY bar.LaneID),2) AS NUMERIC(10,2)) - CAST(ROUND(1.5 * (CAST(ROUND(Percentile_Cont(0.75) WITHIN GROUP(ORDER BY bar.AllInCost ASC) OVER(PARTITION BY bar.LaneID),2) AS NUMERIC(10,2)) - 
CAST(ROUND(Percentile_Cont(0.25) WITHIN GROUP(ORDER BY bar.AllInCost ASC) OVER(PARTITION BY bar.LaneID),2) AS NUMERIC(10,2))) ,2) AS NUMERIC(10,2)) AS LCL,
CAST(ROUND(Percentile_Cont(0.75) WITHIN GROUP(ORDER BY bar.AllInCost ASC) OVER(PARTITION BY bar.LaneID),2) AS NUMERIC(10,2)) + CAST(ROUND(1.5 * (CAST(ROUND(Percentile_Cont(0.75) WITHIN GROUP(ORDER BY bar.AllInCost ASC) OVER(PARTITION BY bar.LaneID),2) AS NUMERIC(10,2)) - 
CAST(ROUND(Percentile_Cont(0.25) WITHIN GROUP(ORDER BY bar.AllInCost ASC) OVER(PARTITION BY bar.LaneID),2) AS NUMERIC(10,2))) ,2) AS NUMERIC(10,2)) AS UCL
FROM USCTTDEV.dbo.tblBidAppRatesRFP2021 bar
ORDER BY bar.LaneID ASC