SELECT
CAST(ald.AddedOn AS DATE) AS 'Added On Date', 
CAST(ald.LastUpdated AS DATE) AS 'Last Updated Date',
ald.CARR_CD AS 'Carrier - Parent Code',
ald.NAME AS 'Carrier - Parent Name',
ald.SRVC_CD AS 'Carrier - Service Code',
ald.SRVC_DESC AS 'Carrier - Service Name',
ald.CUR_OPTLSTAT_ID AS 'Current Status Code',
ald.STATUS AS 'Current Status Description',
CAST(DATEADD(yy, DATEDIFF(yy, 0, ald.CRTD_DTT), 0) AS DATE) AS 'Load Created Year',
CAST(DATEADD(q, DATEDIFF(q, 0, ald.CRTD_DTT), 0) AS DATE) AS 'Load Created Quarter',
CAST(DATEADD(m, DATEDIFF(m, 0, ald.CRTD_DTT), 0) AS DATE) AS 'Load Created Month',
DATEADD(dd, -datepart(dw, CAST(ald.CRTD_DTT AS DATE)) + 1, CAST(ald.CRTD_DTT AS DATE)) AS 'Load Created Week',
CAST(ald.CRTD_DTT AS DATE) AS 'Load Created Date',
CAST(DATEADD(yy, DATEDIFF(yy, 0, ald.STRD_DTT), 0) AS DATE) AS 'Load Started Year',
CAST(DATEADD(q, DATEDIFF(q, 0, ald.STRD_DTT), 0) AS DATE) AS 'Load Started Quarter',
CAST(DATEADD(m, DATEDIFF(m, 0, ald.STRD_DTT), 0) AS DATE) AS 'Load Started Month',
DATEADD(dd, -datepart(dw, CAST(ald.STRD_DTT AS DATE)) + 1, CAST(ald.STRD_DTT AS DATE)) AS 'Load Started Week',
CAST(ald.STRD_DTT AS DATE) AS 'Load Started Date',
CAST(DATEADD(yy, DATEDIFF(yy, 0, ald.SHPD_DTT), 0) AS DATE) AS 'Load Shipped Year',
CAST(DATEADD(q, DATEDIFF(q, 0, ald.SHPD_DTT), 0) AS DATE) AS 'Load Shipped Quarter',
CAST(DATEADD(m, DATEDIFF(m, 0, ald.SHPD_DTT), 0) AS DATE) AS 'Load Shipped Month',
DATEADD(dd, -datepart(dw, CAST(ald.SHPD_DTT AS DATE)) + 1, CAST(ald.SHPD_DTT AS DATE)) AS 'Load Shipped Week',
CAST(ald.SHPD_DTT AS DATE) AS 'Load Shipped Date',
CAST(DATEADD(yy, DATEDIFF(yy, 0, ald.DLVY_DTT), 0) AS DATE) AS 'Load Delivered Year',
CAST(DATEADD(q, DATEDIFF(q, 0, ald.DLVY_DTT), 0) AS DATE) AS 'Load Delivered Quarter',
CAST(DATEADD(m, DATEDIFF(m, 0, ald.DLVY_DTT), 0) AS DATE) AS 'Load Delivered Month',
DATEADD(dd, -datepart(dw, CAST(ald.DLVY_DTT AS DATE)) + 1, CAST(ald.DLVY_DTT AS DATE)) AS 'Load Delivered Week',
CAST(ald.DLVY_DTT AS DATE) AS 'Load Delivered Date',
LD_LEG_ID AS 'Load Number',
CAST(LD_LEG_ID AS NVARCHAR(20)) AS 'Load Number Text',
ald.FRST_SHPG_LOC_CD AS 'Origin Location Code',
ald.FRST_SHPG_LOC_NAME AS 'Origin Location Name',
ald.FRST_CTY_NAME AS 'Origin City Name',
ald.FRST_STA_CD AS 'Origin State',
ald.FRST_PSTL_CD AS 'Origin Postal Code',
ald.FRST_CTRY_CD AS 'Origin Country',
ald.LAST_SHPG_LOC_CD AS 'Destination Location Code',
ald.LAST_SHPG_LOC_NAME AS 'Destination Location Name',
ald.DestCity AS 'Destination City Name',
ald.LAST_STA_CD AS 'Destination State',
ald.LAST_PSTL_CD AS 'Destination Postal Code',
ald.LAST_CTRY_CD AS 'Destination Country',
ald.EQMT_TYP AS 'Equipment Type',
ald.FIXD_ITNR_DIST AS 'Miles',
ald.TOT_TOT_PCE AS 'Total Pieces',
ald.ACTL_CHGD_AMT_DLR AS 'Actual Charged Amount',
ald.CORP1_ID AS 'Corp 1 ID',
ald.MARKETPLACE_CATCHALL AS 'Marketplace Catchall Flag',
ald.STOPS AS 'Stops',
ald.SHIP_CONDITION AS 'Ship Condition',
ald.PreRate_Accessorials AS 'Pre-Rate Accessorials',
ald.PreRate_Fuel AS 'Pre-Rate Fuel',
ald.PreRate_Linehaul AS 'Pre-Rate Linehaul',
ald.PreRate_Repo AS 'Pre-Rate Repo',
ald.PreRate_ZUSB AS 'Pre-Rate ZUSB',
ald.PreRate_ZSPT AS 'Pre-Rate ZSPT',
ald.PreRateCharge AS 'Pre-Rate Charge Flag',
ald.Act_Accessorials AS 'Actual Accessorials',
ald.Act_Fuel AS 'Actual Fuel',
ald.Act_Linehaul AS 'Actual Linehaul',
ald.Act_Repo AS 'Actual Repo',
ald.Act_ZUSB AS 'Actual ZUSB',
ald.Act_ZSPT AS 'Actual ZSPT',
ald.ActualRateCharge AS 'Actual Charge Flag',
ald.OrderType AS 'Order Type',
ald.CarrierManager AS 'Carrier Manager',
ald.Region AS 'Region',
ald.BU AS 'Business Unit (BU)',
ald.ShipMode AS 'Ship Mode',
ald.Origin_Zone AS 'Origin Zone Code',
ald.Dest_Zone AS 'Destination Zone Code',
ald.Lane AS 'Lane',
ald.OriginPlant AS 'Origin Hierarchy Code',
ald.DestinationPlant AS 'Customer Hierarchy Code',
ald.CustomerHierarchy AS 'Customer Hierarchy',
ald.CustomerGroup AS 'Customer Group',
ald.ConsumerWeight AS 'Consumer Weight',
ald.KCPWeight AS 'KCP Weight',
ald.NonWovenWeight AS 'Non-Woven Weight',
ald.UnknownWeight AS 'Unknown Weight',
ald.ConsumerVolume AS 'Consumner Volume',
ald.KCPVolume AS 'KCP Volume',
ald.NonWovenVolume AS 'Non-Woven Volume',
ald.UnknownVolume AS 'Unknown Volume',
ald.OrderCount AS 'Shipment Count',
ald.BUCount AS 'Business Unit (BU) Count)',
ald.TotalWeight AS 'Total Weight',
ald.TotalVolume AS 'Total Volume',
ald.TotalCost AS 'Total Cost',
ald.ConsumerTotalCost AS 'Consumer Total Cost',
ald.ConsumerLinehaulCost AS 'Consumer Linehaul Cost',
ald.ConsumerFuelCost AS 'Consumer Fuel Cost',
ald.ConsumerAccessorialsCost AS 'Consumer Accessorial Cost',
ald.KCPTotalCost AS 'KCP Total Cost',
ald.KCPLinehaulCost AS 'KCP Linehaul Cost',
ald.KCPFuelCost AS 'KCP Fuel Cost',
ald.KCPAccessorialsCost AS 'KCP Accessorials Cost',
ald.NonWovenTotalCost AS 'Non-Woven Total Cost',
ald.NonWovenLinehaulCost AS 'Non-Woven Linehaul Cost',
ald.NonWovenFuelCost AS 'Non-Woven Fuel Cost',
ald.NonWovenAccessorialsCost AS 'Non-Woven Accessorial Cost',
ald.UnknownTotalCost AS 'Unknown Total Cost',
ald.UnknownLinehaulCost AS 'Unknown Linehaul Cost',
ald.UnknownFuelCost AS 'Unknown Fuel Cost',
ald.UnknownAccessorialsCost AS 'Unknown Accessorial Cost',
ald.FRAN AS 'Freight Auction (FRAN) Flag',
ald.RFT AS 'Right First Time (RFT) Flag',
ald.AwardLane AS 'Award Lane Flag',
ald.AwardCarrier AS 'Award Carrier Flag',
ald.Broker AS 'Broker Flag',
ald.Spacemaker AS 'Spacemaker Flag',
ald.WeightedAwardRPM AS 'Weighted Award RPM',
ald.BUSegment AS 'Business Unit (BU) Segment'
FROM USCTTDEV.dbo.tblActualLoadDetail ald
