DROP TABLE IF EXISTS ##tblChangelogTemp

/*
Create temp table
*/
CREATE TABLE ##tblChangelogTemp(
LaneID NVARCHAR(20),
Lane NVARCHAR(50),
ChangeType NVARCHAR(20),
ChangeReason NVARCHAR(50),
SCAC NVARCHAR(10),
Field NVARCHAR(10),
PreviousValue NVARCHAR(10),
NewValue NVARCHAR(10),
UpdatedBy NVARCHAR(50),
UpdatedByName NVARCHAR(50),
UpdatedOn Datetime
)

/*
Insert lanes into Temp Table
SELECT * FROM ##tblChangelogTemp WHERE PreviousValue IS NULL
SELECT DISTINCT ChangeType FROM USCTTDEV.dbo.tblBidAppChangelog
SELECT DISTINCT ChangeReason FROM USCTTDEV.dbo.tblBidAppChangelog
SELECT DISTINCT Field FROM USCTTDEV.dbo.tblBidAppChangelog
SELECT TOP 10 * FROM USCTTDEV.dbo.tblBidAppChangelog
S
*/
INSERT INTO ##tblChangelogTemp (LaneID, Lane, ChangeType, ChangeReason, SCAC, Field, PreviousValue, NewValue, UpdatedBy, UpdatedByName, UpdatedOn)
SELECT bar.LaneID, remove.Lane, 'Rate Level - Mass', 'Mass Update Award Percent', remove.SCAC, 'AWARD_PCT', bar.AWARD_PCT, 0, 
'B40962', 'Stelios Chrysandreas', GETDATE()
FROM 
(
SELECT 'AQSM' AS SCAC, 'KCILROME-KCP-5MA01434' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KCILROME-KCP-5NE68803' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KCILROME-KCP-5NH03109' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KCILROME-KCP-5NY10474' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KCILROME-KCP-5NY12051' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KCILROME-KCP-5PA15056' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KCILROME-KCP-5PA15086' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KCILROME-KCP-5PA15205' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KCILROME-KCP-5PA15601' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KCILROME-KCP-5VA22630' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KCILROME-KCP-5VA23236' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KCILROME-KCP-5VA24153' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KCILROME-NOF-5NH03275' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KCILROME-NOF-5NY10474' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KCILROME-NOF-5NY11236' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KCILROME-NOF-5NY11356' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KCILROME-NOF-5NY11714' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KCILROME-NOF-5PA15205' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KCILROME-NOF-5PA15301' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KCILROME-NOF-5PA15672' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KCILROME-NOF-5PA15801' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KCILROME-NOF-5PA16635' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KCILROME-NOF-5WV25428' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5CT06460' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5FL32210' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5MA01510' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5MA01701' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5MA01876' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5MA02019' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5MA02048' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5MA02210' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5MA02720' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5MA02780' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5MD20701' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5MD20785' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5MD20794' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5MD21046' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5MD21076' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5NH03063' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5NJ07727' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5NJ08016' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5NJ08831' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5NJ08861' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5NY10573' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5NY10941' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5NY12010' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5NY12205' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5NY12302' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5NY13021' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5NY13209' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5NY14086' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5PA17015' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5PA17043' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5PA17055' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5PA17339' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5PA17406' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5PA19020' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5PA19114' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5PA19116' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5PA19460' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'KYOWENSB-5TX75172' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'WICLINTO-5NC27263' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'WICLINTO-5NY13021' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'WICLINTO-5PA18517' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'WICLINTO-5PA19555' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'WIHOBART-5NC27263' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'WIHOBART-5NY13021' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'WIHOBART-5PA19555' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'WIMARINE-5CT06382' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'WIMARINE-5GA30518' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'WIMARINE-5MA02038' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'WIMARINE-5NY13021' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'WIMARINE-5PA17517' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'WIMARINE-5TN37209' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'WIHOBART-5PA19013' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'WIMARINE-5CT06776' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'WIMARINE-5PA19555' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'WINEENAH-5CT06776' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'WINEENAH-5IL60031' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'WINEENAH-5IL60411' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'WINEENAH-5PA19555' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'NCHENVIL-5IN46802' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'WIGREENB-5CT06776' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5CT06460' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5IL60061' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5IL61264' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5MA01701' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5MA01876' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5MA02745' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5MD20774' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5MN56304' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5NJ07047' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5NJ08057' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5NY10454' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5NY10573' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5NY11550' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5NY12010' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5NY13021' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5PA15086' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5PA17241' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5PA17517' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5PA17824' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5PA18045' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5PA18503' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5PA18974' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5PA19057' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5PA19114' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5PA19116' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TNLOUDON-5PA19460' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'OKJENKS-5AL36108' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'OKJENKS-5MN55343' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'OKJENKS-5MN55811' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'OKJENKS-5MN56303' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'OKJENKS-5MN56721' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'OKJENKS-5NC27410' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'OKJENKS-5PA17225' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'OKJENKS-5WA99217' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TXLAREDO-5AL36610' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TXLAREDO-5AR72032' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TXLAREDO-5GA30906' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TXLAREDO-5PA19555' AS LANE UNION ALL
SELECT 'AQSM' AS SCAC, 'TXLAREDO-5GA30253' AS LANE) remove 
LEFT JOIN USCTTDEV.dbo.tblBidAppRatesRFP2021 bar ON bar.Lane = remove.Lane
AND bar.SCAC = remove.SCAC
ORDER BY bar.LaneID ASC, bar.SCAC ASC

/*
Delete where there's no Previous Value 
Lane was already not awarded
SELECT * FROM ##tblChangelogTemp WHERE PreviousValue IS NULL
*/
DELETE FROM ##tblChangelogTemp WHERE PreviousValue IS NULL

/*
Update Bid App Rates table to remove award loads/pct
*/
UPDATE USCTTDEV.dbo.tblBidAppRatesRFP2021
SET AWARD_LDS = NULL,
AWARD_PCT = NULL
FROM USCTTDEV.dbo.tblBidAppRatesRFP2021 bar
INNER JOIN ##tblChangelogTemp clt ON clt.LaneID = bar.LaneID
AND clt.SCAC = bar.SCAC

/*
View table just before appending!
*/
SELECT * FROM ##tblChangelogTemp
ORDER BY LaneID ASC, SCAC ASC

/*
Append changes into changelog
*/
INSERT INTO USCTTDEV.dbo.tblBIdAppChangelog(LaneID, Lane, ChangeType, ChangeReason, SCAC, Field, PreviousValue, NewValue, UpdatedBy, UpdatedByName, UpdatedOn, ChangeTable)
SELECT clt.LaneID,
clt.Lane,
clt.ChangeType, 
clt.ChangeReason,
clt.SCAC,
clt.Field,
clt.PreviousValue,
clt.NewValue,
clt.UpdatedBy,
clt.UpdatedByName,
clt.UpdatedOn,
'tblBidAppRatesRFP2021'
FROM ##tblChangelogTemp clt
LEFT JOIN USCTTDEV.dbo.tblBIdAppChangelog cl ON clt.LaneID = cl.LaneID
AND cl.SCAC = clt.SCAC
AND CAST(cl.UpdatedOn AS DATE) = CAST(clt.UpdatedOn AS DATE)
WHERE cl.LaneID IS NULL
AND cl.SCAC IS NULL
ORDER BY clt.LaneID ASC, clt.SCAC ASC

/*
Execute stored procedures
*/
EXEC USCTTDEV.dbo.sp_AwardWeightedAveragesRFP

EXEC USCTTDEV.dbo.sp_BidAppRatesRank