SELECT DISTINCT
/*ABPP_LD_RFRC_T.LOAD_ID AS LOAD_NUMBER,*/
ABPP_LD_RFRC_T.BSN_UNITS AS BusUnitID,
ABPP_LD_RFRC_T.BSN_UNIT_BY_WGT AS BusUnitWgt,
CASE WHEN ABPP_LD_RFRC_T.UNIT_DESC_BY_WGT IS NULL THEN missingBU.BusinessUnit
ELSE ABPP_LD_RFRC_T.UNIT_DESC_BY_WGT END AS BusinessUnit,
LOAD_LEG_DETAIL_R.LD_LEG_ID as LoadNumber,
LOAD_LEG_DETAIL_R.DLVY_STOP_SEQ_NUM as StopNumber,
LOAD_LEG_R.STRD_DTT as StartDate,
LOAD_LEG_R.SHPD_DTT as ShipDate,				
LOAD_LEG_DETAIL_R.TO_SHPG_LOC_CD as DestinationID,
LOAD_LEG_DETAIL_R.TO_SHPG_LOC_NAME as DestinationName,
LOAD_LEG_DETAIL_R.TO_CTY_NAME as DestinationCity,
LOAD_LEG_DETAIL_R.TO_STA_CD as DestinationState,
LOAD_LEG_DETAIL_R.TO_PSTL_CD as DestinationPostalCd,
LOAD_LEG_R.FRST_SHPG_LOC_CD as OriginID,
LOAD_LEG_R.FRST_SHPG_LOC_NAME as OriginName,
LOAD_LEG_R.FRST_CTY_NAME as OriginCity,
LOAD_LEG_R.FRST_STA_CD as OriginState,
LOAD_LEG_R.FRST_PSTL_CD as OriginPostalCd,
SHIPMENT_R.FRM_DLVY_DTT,
delivered.DeliveryDate,
firstAppt.UserID,
firstAppt.Name AS UserName,
firstAppt.ApptStatus,
firstAppt.ApptFromDtt AS ConfFromDate,
firstAppt.ApptToDtt AS ConfToDate,
firstAppt.ReasonCode,
firstAppt.ReasonDesc,
CASE WHEN delivered.DeliveryDate IS NULL THEN 0 ELSE 1 END AS DeliveryCnt,
CASE WHEN CAST(firstAppt.ApptFromDate AS DATE) <> CAST(delivered.DeliveryDate AS DATE) AND delivered.DeliveryDate IS NOT NULL THEN 1 ELSE 0 END AS DateChange
FROM
NAJDAADM.LOAD_LEG_R LOAD_LEG_R

INNER JOIN NAJDATRN.ABPP_LD_RFRC_T ABPP_LD_RFRC_T ON
ABPP_LD_RFRC_T.LOAD_ID = LOAD_LEG_R.LD_LEG_ID AND
ABPP_LD_RFRC_T.BSN_UNIT_BY_WGT Is Not Null

INNER JOIN NAJDAADM.LOAD_LEG_DETAIL_R LOAD_LEG_DETAIL_R ON LOAD_LEG_DETAIL_R.LD_LEG_ID = LOAD_LEG_R.LD_LEG_ID
AND (substr(LOAD_LEG_DETAIL_R.TO_SHPG_LOC_CD,1,8) Not In ('58005914','58004952','58005988','58003441','58003411')) AND
(LOAD_LEG_DETAIL_R.DLVY_STOP_SEQ_NUM > 1) AND	
(LOAD_LEG_DETAIL_R.TO_PNT_TYP_ENU='Distribution Center')

INNER JOIN NAJDAADM.DISTRIBUTION_CENTER_R DISTRIBUTION_CENTER_R ON LOAD_LEG_DETAIL_R.TO_SHPG_LOC_CD = DISTRIBUTION_CENTER_R.SHPG_LOC_CD
AND DISTRIBUTION_CENTER_R.APT_RQRD_YN='Y'

INNER JOIN NAJDAADM.SHIPMENT_R SHIPMENT_R ON LOAD_LEG_DETAIL_R.LD_LEG_ID = LOAD_LEG_R.LD_LEG_ID AND
LOAD_LEG_DETAIL_R.SHPM_ID = SHIPMENT_R.SHPM_ID AND
LOAD_LEG_DETAIL_R.SHPM_NUM = SHIPMENT_R.SHPM_NUM

LEFT JOIN (
SELECT '2810' AS BusinessUnitID, 'CONSUMER' AS BusinessUnit FROM DUAL UNION ALL
SELECT '2811' AS BusinessUnitID, 'KCP' AS BusinessUnit FROM DUAL UNION ALL
SELECT '2820' AS BusinessUnitID, 'CONSUMER' AS BusinessUnit FROM DUAL UNION ALL
SELECT '2821' AS BusinessUnitID, 'KCP' AS BusinessUnit FROM DUAL UNION ALL
SELECT 'Z01' AS BusinessUnitID, 'CONSUMER' AS BusinessUnit FROM DUAL UNION ALL
SELECT 'Z02' AS BusinessUnitID, 'KCP' AS BusinessUnit FROM DUAL UNION ALL
SELECT 'Z04' AS BusinessUnitID, 'KCP' AS BusinessUnit FROM DUAL UNION ALL
SELECT 'Z05' AS BusinessUnitID, 'NON WOVENS' AS BusinessUnit FROM DUAL UNION ALL
SELECT 'Z06' AS BusinessUnitID, 'KCP' AS BusinessUnit FROM DUAL UNION ALL
SELECT 'Z07' AS BusinessUnitID, 'KCP' AS BusinessUnit FROM DUAL
)missingBU ON missingBU.BusinessUnitID = ABPP_LD_RFRC_T.BSN_UNIT_BY_WGT

LEFT JOIN (
SELECT firstAppt.LOAD_NUMBER,
firstAppt.STOP_NUMBER,
firstAppt.ApptStatus,
firstAppt.ApptChgDateTime,
firstAppt.UserID,
firstAppt.Name,
firstAppt.ApptFromDtt,
firstAppt.ApptToDtt,
firstAppt.ReasonCode,
firstAppt.ReasonDesc
FROM (
SELECT DISTINCT
ROW_NUMBER() OVER (PARTITION BY ABPP_OTC_APPOINTMENTHISTORY.LOAD_NUMBER, ABPP_OTC_APPOINTMENTHISTORY.STOP_NUMBER ORDER BY ABPP_OTC_APPOINTMENTHISTORY.APPOINTMENT_CHANGE_TIME ASC) AS Ranking,
ABPP_OTC_APPOINTMENTHISTORY.LOAD_NUMBER,
ABPP_OTC_APPOINTMENTHISTORY.STOP_NUMBER,
ABPP_OTC_APPOINTMENTHISTORY.APPOINTMENT_STATUS AS ApptStatus,
ABPP_OTC_APPOINTMENTHISTORY.APPOINTMENT_CHANGE_TIME as ApptChgDateTime,
ABPP_OTC_APPOINTMENTHISTORY.APPOINTMENT_CHANGED_BY as UserID,
USR_T.Name,
ABPP_OTC_APPOINTMENTHISTORY.APPOINTMENT_FROM_TIME as ApptFromDtt,
ABPP_OTC_APPOINTMENTHISTORY.APPOINTMENT_TO_TIME as ApptToDtt,
ABPP_OTC_APPOINTMENTHISTORY.REASON_CODE as ReasonCode,
ABPP_OTC_APPOINTMENTHISTORY.REASON_DESC as ReasonDesc

FROM
TRN_APPT.ABPP_OTC_APPOINTMENTHISTORY ABPP_OTC_APPOINTMENTHISTORY
INNER JOIN NAI2PADM.USR_T USR_T ON USR_T.USR_CD = ABPP_OTC_APPOINTMENTHISTORY.APPOINTMENT_CHANGED_BY

WHERE
(ABPP_OTC_APPOINTMENTHISTORY.APPOINTMENT_CHANGE_TIME>=add_months(trunc(sysdate,'mm'),-4)) AND
(ABPP_OTC_APPOINTMENTHISTORY.STOP_NUMBER>'1') AND
(ABPP_OTC_APPOINTMENTHISTORY.APPOINTMENT_STATUS ='Confirmed')
/*AND LOAD_NUMBER = '519978032'*/

GROUP BY LOAD_NUMBER,
STOP_NUMBER,
APPOINTMENT_STATUS,
APPOINTMENT_CHANGE_TIME,
APPOINTMENT_CHANGED_BY,
Name,
APPOINTMENT_FROM_TIME,
APPOINTMENT_TO_TIME,
REASON_CODE,
REASON_DESC
) firstAppt
WHERE firstAppt.Ranking = 1
)firstAppt ON firstAppt.LOAD_NUMBER = LOAD_LEG_DETAIL_R.LD_LEG_ID
AND firstAppt.STOP_NUMBER = LOAD_LEG_DETAIL_R.DLVY_STOP_SEQ_NUM


LEFT JOIN (
SELECT 
MAX(LD_LEG_ID) AS LD_LEG_ID, 
/*SEQ_NUM AS STOP,*/
MAX(DROP_ARVL_RPTD_DTT) AS DeliveryDate
FROM 
NAJDAADM.stop_r
WHERE SEQ_NUM <> 1
AND DROP_ARVL_RPTD_DTT >= add_months(trunc(sysdate,'mm'),-4)
/*AND LD_LEG_ID = '520576564'*/
GROUP BY LD_LEG_ID/*, SEQ_NUM*/
)delivered ON delivered.LD_LEG_ID = LOAD_LEG_R.LD_LEG_ID


WHERE LOAD_LEG_R.SHPD_DTT>=add_months(trunc(sysdate,'MM'),-2) AND
LOAD_LEG_R.EQMT_TYP In ('48FT','48TC','53FT','53TC','53HC','53IM','53RT') AND
LOAD_LEG_R.FRST_CTRY_CD In ('USA','CAN') AND
LOAD_LEG_R.LAST_CTRY_CD In ('USA','CAN')